# *Introduction*


This Notebook consists of:
1. txt to csv data conversion
2. data preprocessing (handle null & duplicated values, text cleaning, remove stopwords, shortwords)
3. Lemmetization
4. Doc2Vec
5. K-Means with various K
6. Silhuette score
7. conclusion

# *Import Necessary Dependencies*

In [1]:
!pip install nltk

import numpy as np
import pandas as pd
import os

# Data Preprocessing
import nltk
import re
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('omw-1.4')
nltk.download('wordnet')
from nltk.corpus import stopwords
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from nltk import pos_tag

# Vectorization
!pip install gensim
import gensim
from gensim.models.doc2vec import Doc2Vec

#k-means
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

#ignore warnings
import warnings
warnings.filterwarnings("ignore")

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package wordnet to /root/nltk_data...

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 15.6 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

# Download Data

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("shivamkushwaha/bbc-full-text-document-classification")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'bbc-full-text-document-classification' dataset.
Path to dataset files: /kaggle/input/bbc-full-text-document-classification

# 1. convert text data to csv

In [3]:
import os
for dirname in os.walk('/kaggle/input/bbc-full-text-document-classification'):
        print(dirname)

('/kaggle/input/bbc-full-text-document-classification', ['bbc-fulltext (document classification)', 'bbc'], [])
('/kaggle/input/bbc-full-text-document-classification/bbc-fulltext (document classification)', ['bbc'], [])
('/kaggle/input/bbc-full-text-document-classification/bbc-fulltext (document classification)/bbc', ['politics', 'sport', 'tech', 'entertainment', 'business'], ['README.TXT'])
('/kaggle/input/bbc-full-text-document-classification/bbc-fulltext (document classification)/bbc/politics', [], ['361.txt', '245.txt', '141.txt', '372.txt', '333.txt', '276.txt', '244.txt', '175.txt', '351.txt', '265.txt', '178.txt', '201.txt', '087.txt', '251.txt', '122.txt', '375.txt', '098.txt', '139.txt', '161.txt', '328.txt', '174.txt', '353.txt', '383.txt', '409.txt', '039.txt', '365.txt', '028.txt', '134.txt', '044.txt', '154.txt', '054.txt', '200.txt', '396.txt', '021.txt', '179.txt', '229.txt', '322.txt', '057.txt', '043.txt', '045.txt', '148.txt', '115.txt', '415.txt', '040.txt', '289.txt', '063.txt', '263.txt', '105.txt', '180.txt', '255.txt', '185.txt', '162.txt', '240.txt', '343.txt', '166.txt', '127.txt', '010.txt', '031.txt', '235.txt', '356.txt', '062.txt', '376.txt', '012.txt', '290.txt', '369.txt', '215.txt', '129.txt', '089.txt', '059.txt', '314.txt', '027.txt', '391.txt', '310.txt', '374.txt', '230.txt', '363.txt', '381.txt', '155.txt', '398.txt', '037.txt', '165.txt', '407.txt', '159.txt', '001.txt', '382.txt', '250.txt', '254.txt', '080.txt', '350.txt', '223.txt', '034.txt', '399.txt', '171.txt', '299.txt', '036.txt', '387.txt', '261.txt', '226.txt', '120.txt', '224.txt', '253.txt', '158.txt', '332.txt', '308.txt', '327.txt', '011.txt', '094.txt', '016.txt', '151.txt', '093.txt', '075.txt', '212.txt', '339.txt', '334.txt', '280.txt', '177.txt', '368.txt', '225.txt', '373.txt', '275.txt', '337.txt', '323.txt', '113.txt', '268.txt', '138.txt', '085.txt', '347.txt', '077.txt', '032.txt', '196.txt', '046.txt', '076.txt', '022.txt', '320.txt', '304.txt', '262.txt', '088.txt', '359.txt', '349.txt', '202.txt', '209.txt', '400.txt', '371.txt', '395.txt', '058.txt', '152.txt', '067.txt', '412.txt', '260.txt', '068.txt', '237.txt', '360.txt', '247.txt', '030.txt', '401.txt', '298.txt', '256.txt', '210.txt', '234.txt', '020.txt', '188.txt', '070.txt', '266.txt', '203.txt', '272.txt', '041.txt', '023.txt', '114.txt', '190.txt', '112.txt', '195.txt', '198.txt', '220.txt', '143.txt', '397.txt', '066.txt', '331.txt', '279.txt', '086.txt', '071.txt', '402.txt', '169.txt', '318.txt', '366.txt', '257.txt', '157.txt', '300.txt', '311.txt', '061.txt', '241.txt', '170.txt', '150.txt', '078.txt', '358.txt', '258.txt', '133.txt', '074.txt', '278.txt', '132.txt', '006.txt', '213.txt', '181.txt', '146.txt', '156.txt', '056.txt', '008.txt', '052.txt', '309.txt', '131.txt', '342.txt', '378.txt', '232.txt', '307.txt', '111.txt', '313.txt', '233.txt', '341.txt', '106.txt', '060.txt', '219.txt', '144.txt', '393.txt', '270.txt', '403.txt', '095.txt', '206.txt', '007.txt', '338.txt', '301.txt', '335.txt', '186.txt', '410.txt', '273.txt', '228.txt', '321.txt', '038.txt', '167.txt', '274.txt', '118.txt', '357.txt', '014.txt', '416.txt', '221.txt', '083.txt', '193.txt', '125.txt', '128.txt', '199.txt', '108.txt', '172.txt', '130.txt', '302.txt', '140.txt', '259.txt', '284.txt', '317.txt', '204.txt', '267.txt', '003.txt', '216.txt', '271.txt', '312.txt', '184.txt', '388.txt', '107.txt', '064.txt', '408.txt', '164.txt', '386.txt', '082.txt', '242.txt', '100.txt', '297.txt', '160.txt', '249.txt', '417.txt', '316.txt', '243.txt', '145.txt', '236.txt', '305.txt', '287.txt', '084.txt', '296.txt', '294.txt', '394.txt', '048.txt', '090.txt', '189.txt', '096.txt', '315.txt', '103.txt', '072.txt', '017.txt', '002.txt', '370.txt', '069.txt', '135.txt', '102.txt', '293.txt', '123.txt', '227.txt', '346.txt', '379.txt', '362.txt', '222.txt', '018.txt', '047.txt', '079.txt', '009.txt', '183.txt', '049.txt', '364.txt', '035.txt', '218.txt', '101.txt', '081.txt', '292.txt', '264.txt', '330.txt', '194.txt', '015.txt', '124.txt', '025.txt', '405.txt', '404.txt', '277.txt', '367.txt', '329.txt', '238.txt', '168.txt', '390.txt', '392.txt', '291.txt', '288.txt', '324.txt', '005.txt', '345.txt', '147.txt', '295.txt', '153.txt', '211.txt', '205.txt', '384.txt', '099.txt', '197.txt', '281.txt', '326.txt', '117.txt', '121.txt', '163.txt', '306.txt', '187.txt', '252.txt', '352.txt', '182.txt', '355.txt', '411.txt', '389.txt', '137.txt', '026.txt', '303.txt', '065.txt', '104.txt', '406.txt', '051.txt', '325.txt', '029.txt', '354.txt', '207.txt', '414.txt', '191.txt', '091.txt', '109.txt', '033.txt', '055.txt', '136.txt', '176.txt', '053.txt', '092.txt', '073.txt', '246.txt', '019.txt', '217.txt', '348.txt', '119.txt', '042.txt', '116.txt', '013.txt', '231.txt', '377.txt', '282.txt', '344.txt', '319.txt', '269.txt', '286.txt', '173.txt', '097.txt', '126.txt', '142.txt', '340.txt', '239.txt', '208.txt', '285.txt', '214.txt', '149.txt', '050.txt', '336.txt', '413.txt', '110.txt', '385.txt', '283.txt', '380.txt', '192.txt', '248.txt', '004.txt', '024.txt'])
('/kaggle/input/bbc-full-text-document-classification/bbc-fulltext (document classification)/bbc/sport', [], ['361.txt', '245.txt', '431.txt', '141.txt', '487.txt', '372.txt', '333.txt', '276.txt', '244.txt', '175.txt', '351.txt', '418.txt', '449.txt', '265.txt', '178.txt', '201.txt', '464.txt', '087.txt', '251.txt', '122.txt', '375.txt', '098.txt', '139.txt', '161.txt', '479.txt', '328.txt', '174.txt', '353.txt', '383.txt', '426.txt', '409.txt', '039.txt', '365.txt', '028.txt', '134.txt', '044.txt', '154.txt', '054.txt', '200.txt', '396.txt', '021.txt', '468.txt', '179.txt', '453.txt', '472.txt', '229.txt', '322.txt', '057.txt', '043.txt', '045.txt', '148.txt', '115.txt', '415.txt', '459.txt', '040.txt', '289.txt', '063.txt', '263.txt', '105.txt', '180.txt', '255.txt', '185.txt', '162.txt', '240.txt', '343.txt', '166.txt', '127.txt', '010.txt', '031.txt', '235.txt', '356.txt', '062.txt', '376.txt', '478.txt', '012.txt', '290.txt', '369.txt', '483.txt', '215.txt', '129.txt', '450.txt', '503.txt', '089.txt', '059.txt', '314.txt', '027.txt', '391.txt', '310.txt', '374.txt', '230.txt', '501.txt', '363.txt', '381.txt', '155.txt', '398.txt', '037.txt', '165.txt', '457.txt', '407.txt', '510.txt', '159.txt', '001.txt', '382.txt', '447.txt', '250.txt', '254.txt', '080.txt', '350.txt', '223.txt', '034.txt', '399.txt', '171.txt', '299.txt', '036.txt', '387.txt', '261.txt', '226.txt', '120.txt', '224.txt', '253.txt', '158.txt', '425.txt', '332.txt', '308.txt', '327.txt', '011.txt', '094.txt', '485.txt', '016.txt', '151.txt', '093.txt', '075.txt', '212.txt', '339.txt', '334.txt', '280.txt', '490.txt', '177.txt', '368.txt', '225.txt', '373.txt', '275.txt', '337.txt', '481.txt', '462.txt', '323.txt', '113.txt', '268.txt', '138.txt', '085.txt', '347.txt', '077.txt', '435.txt', '032.txt', '196.txt', '423.txt', '488.txt', '046.txt', '076.txt', '022.txt', '320.txt', '304.txt', '506.txt', '262.txt', '452.txt', '088.txt', '359.txt', '349.txt', '202.txt', '209.txt', '400.txt', '473.txt', '441.txt', '461.txt', '371.txt', '395.txt', '058.txt', '152.txt', '471.txt', '507.txt', '067.txt', '412.txt', '260.txt', '498.txt', '068.txt', '505.txt', '237.txt', '421.txt', '360.txt', '247.txt', '030.txt', '401.txt', '298.txt', '256.txt', '210.txt', '234.txt', '020.txt', '430.txt', '188.txt', '070.txt', '266.txt', '420.txt', '203.txt', '491.txt', '272.txt', '041.txt', '023.txt', '114.txt', '422.txt', '440.txt', '190.txt', '112.txt', '195.txt', '198.txt', '220.txt', '143.txt', '397.txt', '066.txt', '331.txt', '279.txt', '086.txt', '071.txt', '402.txt', '169.txt', '434.txt', '318.txt', '366.txt', '257.txt', '157.txt', '428.txt', '300.txt', '311.txt', '061.txt', '241.txt', '475.txt', '170.txt', '150.txt', '078.txt', '358.txt', '258.txt', '133.txt', '074.txt', '278.txt', '132.txt', '006.txt', '213.txt', '181.txt', '146.txt', '156.txt', '056.txt', '008.txt', '427.txt', '052.txt', '309.txt', '445.txt', '131.txt', '342.txt', '378.txt', '232.txt', '489.txt', '436.txt', '307.txt', '111.txt', '313.txt', '233.txt', '341.txt', '106.txt', '060.txt', '480.txt', '432.txt', '219.txt', '144.txt', '393.txt', '270.txt', '403.txt', '095.txt', '206.txt', '007.txt', '338.txt', '301.txt', '451.txt', '335.txt', '477.txt', '186.txt', '410.txt', '470.txt', '495.txt', '273.txt', '228.txt', '321.txt', '038.txt', '167.txt', '274.txt', '118.txt', '357.txt', '467.txt', '014.txt', '416.txt', '221.txt', '083.txt', '455.txt', '193.txt', '125.txt', '128.txt', '199.txt', '108.txt', '172.txt', '130.txt', '302.txt', '140.txt', '259.txt', '433.txt', '284.txt', '317.txt', '204.txt', '267.txt', '003.txt', '492.txt', '216.txt', '271.txt', '443.txt', '312.txt', '486.txt', '184.txt', '388.txt', '107.txt', '474.txt', '064.txt', '408.txt', '164.txt', '386.txt', '082.txt', '242.txt', '100.txt', '297.txt', '160.txt', '249.txt', '417.txt', '316.txt', '243.txt', '145.txt', '236.txt', '305.txt', '287.txt', '084.txt', '296.txt', '294.txt', '496.txt', '394.txt', '048.txt', '482.txt', '090.txt', '189.txt', '096.txt', '315.txt', '103.txt', '072.txt', '017.txt', '454.txt', '500.txt', '002.txt', '370.txt', '069.txt', '135.txt', '102.txt', '293.txt', '123.txt', '227.txt', '429.txt', '346.txt', '379.txt', '362.txt', '493.txt', '222.txt', '018.txt', '047.txt', '079.txt', '497.txt', '465.txt', '499.txt', '504.txt', '009.txt', '183.txt', '049.txt', '364.txt', '035.txt', '218.txt', '442.txt', '101.txt', '081.txt', '511.txt', '292.txt', '264.txt', '330.txt', '194.txt', '015.txt', '419.txt', '124.txt', '025.txt', '405.txt', '404.txt', '277.txt', '466.txt', '439.txt', '367.txt', '329.txt', '238.txt', '502.txt', '168.txt', '390.txt', '476.txt', '446.txt', '392.txt', '291.txt', '288.txt', '324.txt', '005.txt', '509.txt', '345.txt', '147.txt', '295.txt', '153.txt', '458.txt', '211.txt', '205.txt', '384.txt', '099.txt', '197.txt', '281.txt', '326.txt', '117.txt', '121.txt', '163.txt', '306.txt', '187.txt', '252.txt', '352.txt', '182.txt', '355.txt', '411.txt', '389.txt', '137.txt', '026.txt', '303.txt', '438.txt', '065.txt', '104.txt', '406.txt', '051.txt', '325.txt', '424.txt', '029.txt', '354.txt', '207.txt', '414.txt', '191.txt', '091.txt', '109.txt', '033.txt', '055.txt', '469.txt', '136.txt', '176.txt', '508.txt', '053.txt', '092.txt', '456.txt', '073.txt', '246.txt', '019.txt', '217.txt', '348.txt', '494.txt', '119.txt', '042.txt', '460.txt', '463.txt', '437.txt', '116.txt', '013.txt', '231.txt', '444.txt', '377.txt', '484.txt', '282.txt', '344.txt', '319.txt', '269.txt', '286.txt', '173.txt', '097.txt', '126.txt', '142.txt', '340.txt', '239.txt', '208.txt', '285.txt', '214.txt', '149.txt', '050.txt', '448.txt', '336.txt', '413.txt', '110.txt', '385.txt', '283.txt', '380.txt', '192.txt', '248.txt', '004.txt', '024.txt'])
('/kaggle/input/bbc-full-text-document-classification/bbc-fulltext (document classification)/bbc/tech', [], ['361.txt', '245.txt', '141.txt', '372.txt', '333.txt', '276.txt', '244.txt', '175.txt', '351.txt', '265.txt', '178.txt', '201.txt', '087.txt', '251.txt', '122.txt', '375.txt', '098.txt', '139.txt', '161.txt', '328.txt', '174.txt', '353.txt', '383.txt', '039.txt', '365.txt', '028.txt', '134.txt', '044.txt', '154.txt', '054.txt', '200.txt', '396.txt', '021.txt', '179.txt', '229.txt', '322.txt', '057.txt', '043.txt', '045.txt', '148.txt', '115.txt', '040.txt', '289.txt', '063.txt', '263.txt', '105.txt', '180.txt', '255.txt', '185.txt', '162.txt', '240.txt', '343.txt', '166.txt', '127.txt', '010.txt', '031.txt', '235.txt', '356.txt', '062.txt', '376.txt', '012.txt', '290.txt', '369.txt', '215.txt', '129.txt', '089.txt', '059.txt', '314.txt', '027.txt', '391.txt', '310.txt', '374.txt', '230.txt', '363.txt', '381.txt', '155.txt', '398.txt', '037.txt', '165.txt', '159.txt', '001.txt', '382.txt', '250.txt', '254.txt', '080.txt', '350.txt', '223.txt', '034.txt', '399.txt', '171.txt', '299.txt', '036.txt', '387.txt', '261.txt', '226.txt', '120.txt', '224.txt', '253.txt', '158.txt', '332.txt', '308.txt', '327.txt', '011.txt', '094.txt', '016.txt', '151.txt', '093.txt', '075.txt', '212.txt', '339.txt', '334.txt', '280.txt', '177.txt', '368.txt', '225.txt', '373.txt', '275.txt', '337.txt', '323.txt', '113.txt', '268.txt', '138.txt', '085.txt', '347.txt', '077.txt', '032.txt', '196.txt', '046.txt', '076.txt', '022.txt', '320.txt', '304.txt', '262.txt', '088.txt', '359.txt', '349.txt', '202.txt', '209.txt', '400.txt', '371.txt', '395.txt', '058.txt', '152.txt', '067.txt', '260.txt', '068.txt', '237.txt', '360.txt', '247.txt', '030.txt', '401.txt', '298.txt', '256.txt', '210.txt', '234.txt', '020.txt', '188.txt', '070.txt', '266.txt', '203.txt', '272.txt', '041.txt', '023.txt', '114.txt', '190.txt', '112.txt', '195.txt', '198.txt', '220.txt', '143.txt', '397.txt', '066.txt', '331.txt', '279.txt', '086.txt', '071.txt', '169.txt', '318.txt', '366.txt', '257.txt', '157.txt', '300.txt', '311.txt', '061.txt', '241.txt', '170.txt', '150.txt', '078.txt', '358.txt', '258.txt', '133.txt', '074.txt', '278.txt', '132.txt', '006.txt', '213.txt', '181.txt', '146.txt', '156.txt', '056.txt', '008.txt', '052.txt', '309.txt', '131.txt', '342.txt', '378.txt', '232.txt', '307.txt', '111.txt', '313.txt', '233.txt', '341.txt', '106.txt', '060.txt', '219.txt', '144.txt', '393.txt', '270.txt', '095.txt', '206.txt', '007.txt', '338.txt', '301.txt', '335.txt', '186.txt', '273.txt', '228.txt', '321.txt', '038.txt', '167.txt', '274.txt', '118.txt', '357.txt', '014.txt', '221.txt', '083.txt', '193.txt', '125.txt', '128.txt', '199.txt', '108.txt', '172.txt', '130.txt', '302.txt', '140.txt', '259.txt', '284.txt', '317.txt', '204.txt', '267.txt', '003.txt', '216.txt', '271.txt', '312.txt', '184.txt', '388.txt', '107.txt', '064.txt', '164.txt', '386.txt', '082.txt', '242.txt', '100.txt', '297.txt', '160.txt', '249.txt', '316.txt', '243.txt', '145.txt', '236.txt', '305.txt', '287.txt', '084.txt', '296.txt', '294.txt', '394.txt', '048.txt', '090.txt', '189.txt', '096.txt', '315.txt', '103.txt', '072.txt', '017.txt', '002.txt', '370.txt', '069.txt', '135.txt', '102.txt', '293.txt', '123.txt', '227.txt', '346.txt', '379.txt', '362.txt', '222.txt', '018.txt', '047.txt', '079.txt', '009.txt', '183.txt', '049.txt', '364.txt', '035.txt', '218.txt', '101.txt', '081.txt', '292.txt', '264.txt', '330.txt', '194.txt', '015.txt', '124.txt', '025.txt', '277.txt', '367.txt', '329.txt', '238.txt', '168.txt', '390.txt', '392.txt', '291.txt', '288.txt', '324.txt', '005.txt', '345.txt', '147.txt', '295.txt', '153.txt', '211.txt', '205.txt', '384.txt', '099.txt', '197.txt', '281.txt', '326.txt', '117.txt', '121.txt', '163.txt', '306.txt', '187.txt', '252.txt', '352.txt', '182.txt', '355.txt', '389.txt', '137.txt', '026.txt', '303.txt', '065.txt', '104.txt', '051.txt', '325.txt', '029.txt', '354.txt', '207.txt', '191.txt', '091.txt', '109.txt', '033.txt', '055.txt', '136.txt', '176.txt', '053.txt', '092.txt', '073.txt', '246.txt', '019.txt', '217.txt', '348.txt', '119.txt', '042.txt', '116.txt', '013.txt', '231.txt', '377.txt', '282.txt', '344.txt', '319.txt', '269.txt', '286.txt', '173.txt', '097.txt', '126.txt', '142.txt', '340.txt', '239.txt', '208.txt', '285.txt', '214.txt', '149.txt', '050.txt', '336.txt', '110.txt', '385.txt', '283.txt', '380.txt', '192.txt', '248.txt', '004.txt', '024.txt'])
('/kaggle/input/bbc-full-text-document-classification/bbc-fulltext (document classification)/bbc/entertainment', [], ['361.txt', '245.txt', '141.txt', '372.txt', '333.txt', '276.txt', '244.txt', '175.txt', '351.txt', '265.txt', '178.txt', '201.txt', '087.txt', '251.txt', '122.txt', '375.txt', '098.txt', '139.txt', '161.txt', '328.txt', '174.txt', '353.txt', '383.txt', '039.txt', '365.txt', '028.txt', '134.txt', '044.txt', '154.txt', '054.txt', '200.txt', '021.txt', '179.txt', '229.txt', '322.txt', '057.txt', '043.txt', '045.txt', '148.txt', '115.txt', '040.txt', '289.txt', '063.txt', '263.txt', '105.txt', '180.txt', '255.txt', '185.txt', '162.txt', '240.txt', '343.txt', '166.txt', '127.txt', '010.txt', '031.txt', '235.txt', '356.txt', '062.txt', '376.txt', '012.txt', '290.txt', '369.txt', '215.txt', '129.txt', '089.txt', '059.txt', '314.txt', '027.txt', '310.txt', '374.txt', '230.txt', '363.txt', '381.txt', '155.txt', '037.txt', '165.txt', '159.txt', '001.txt', '382.txt', '250.txt', '254.txt', '080.txt', '350.txt', '223.txt', '034.txt', '171.txt', '299.txt', '036.txt', '261.txt', '226.txt', '120.txt', '224.txt', '253.txt', '158.txt', '332.txt', '308.txt', '327.txt', '011.txt', '094.txt', '016.txt', '151.txt', '093.txt', '075.txt', '212.txt', '339.txt', '334.txt', '280.txt', '177.txt', '368.txt', '225.txt', '373.txt', '275.txt', '337.txt', '323.txt', '113.txt', '268.txt', '138.txt', '085.txt', '347.txt', '077.txt', '032.txt', '196.txt', '046.txt', '076.txt', '022.txt', '320.txt', '304.txt', '262.txt', '088.txt', '359.txt', '349.txt', '202.txt', '209.txt', '371.txt', '058.txt', '152.txt', '067.txt', '260.txt', '068.txt', '237.txt', '360.txt', '247.txt', '030.txt', '298.txt', '256.txt', '210.txt', '234.txt', '020.txt', '188.txt', '070.txt', '266.txt', '203.txt', '272.txt', '041.txt', '023.txt', '114.txt', '190.txt', '112.txt', '195.txt', '198.txt', '220.txt', '143.txt', '066.txt', '331.txt', '279.txt', '086.txt', '071.txt', '169.txt', '318.txt', '366.txt', '257.txt', '157.txt', '300.txt', '311.txt', '061.txt', '241.txt', '170.txt', '150.txt', '078.txt', '358.txt', '258.txt', '133.txt', '074.txt', '278.txt', '132.txt', '006.txt', '213.txt', '181.txt', '146.txt', '156.txt', '056.txt', '008.txt', '052.txt', '309.txt', '131.txt', '342.txt', '378.txt', '232.txt', '307.txt', '111.txt', '313.txt', '233.txt', '341.txt', '106.txt', '060.txt', '219.txt', '144.txt', '270.txt', '095.txt', '206.txt', '007.txt', '338.txt', '301.txt', '335.txt', '186.txt', '273.txt', '228.txt', '321.txt', '038.txt', '167.txt', '274.txt', '118.txt', '357.txt', '014.txt', '221.txt', '083.txt', '193.txt', '125.txt', '128.txt', '199.txt', '108.txt', '172.txt', '130.txt', '302.txt', '140.txt', '259.txt', '284.txt', '317.txt', '204.txt', '267.txt', '003.txt', '216.txt', '271.txt', '312.txt', '184.txt', '107.txt', '064.txt', '164.txt', '386.txt', '082.txt', '242.txt', '100.txt', '297.txt', '160.txt', '249.txt', '316.txt', '243.txt', '145.txt', '236.txt', '305.txt', '287.txt', '084.txt', '296.txt', '294.txt', '048.txt', '090.txt', '189.txt', '096.txt', '315.txt', '103.txt', '072.txt', '017.txt', '002.txt', '370.txt', '069.txt', '135.txt', '102.txt', '293.txt', '123.txt', '227.txt', '346.txt', '379.txt', '362.txt', '222.txt', '018.txt', '047.txt', '079.txt', '009.txt', '183.txt', '049.txt', '364.txt', '035.txt', '218.txt', '101.txt', '081.txt', '292.txt', '264.txt', '330.txt', '194.txt', '015.txt', '124.txt', '025.txt', '277.txt', '367.txt', '329.txt', '238.txt', '168.txt', '291.txt', '288.txt', '324.txt', '005.txt', '345.txt', '147.txt', '295.txt', '153.txt', '211.txt', '205.txt', '384.txt', '099.txt', '197.txt', '281.txt', '326.txt', '117.txt', '121.txt', '163.txt', '306.txt', '187.txt', '252.txt', '352.txt', '182.txt', '355.txt', '137.txt', '026.txt', '303.txt', '065.txt', '104.txt', '051.txt', '325.txt', '029.txt', '354.txt', '207.txt', '191.txt', '091.txt', '109.txt', '033.txt', '055.txt', '136.txt', '176.txt', '053.txt', '092.txt', '073.txt', '246.txt', '019.txt', '217.txt', '348.txt', '119.txt', '042.txt', '116.txt', '013.txt', '231.txt', '377.txt', '282.txt', '344.txt', '319.txt', '269.txt', '286.txt', '173.txt', '097.txt', '126.txt', '142.txt', '340.txt', '239.txt', '208.txt', '285.txt', '214.txt', '149.txt', '050.txt', '336.txt', '110.txt', '385.txt', '283.txt', '380.txt', '192.txt', '248.txt', '004.txt', '024.txt'])

In [4]:
DATASET_PATH = '/kaggle/input/bbc-full-text-document-classification/bbc'

rows = []

for category in os.listdir(DATASET_PATH):

    category_path = os.path.join(DATASET_PATH, category)

    if not os.path.isdir(category_path):
        continue

    for file in os.listdir(category_path):

        if not file.endswith(".txt"):
            continue

        file_path = os.path.join(category_path, file)

        try:
            with open(file_path, "r", encoding="latin-1") as f:
                text = f.read()

            rows.append({
                "category": category,
                "filename": file,
                "text": text
            })

        except Exception as e:
            print(f"Error reading {file}: {e}")

df = pd.DataFrame(rows)

print(df.shape)

df.to_csv(
    "bbc_news_dataset.csv",
    index=False
)

print("Saved: bbc_news_dataset.csv")

(2225, 3)
Saved: bbc_news_dataset.csv

In [5]:
news_data = pd.read_csv("bbc_news_dataset.csv")

# 2. Data preprocessing

In [6]:
news_data.head()

   category filename                                               text
0  politics  361.txt  Budget to set scene for election\n\nGordon Bro...
1  politics  245.txt  Army chiefs in regiments decision\n\nMilitary ...
2  politics  141.txt  Howard denies split over ID cards\n\nMichael H...
3  politics  372.txt  Observers to monitor UK election\n\nMinisters ...
4  politics  333.txt  Kilroy names election seat target\n\nEx-chat s...

In [7]:
news_data.category.isnull().sum()

np.int64(0)

In [8]:
news_data.filename.isnull().sum()

np.int64(0)

In [9]:
if "readme" or "README" in news_data.filename :
  print("yes")
else :
  print("no")

yes

In [10]:
# drop rows containing readme.txt in filename
news_data = news_data[news_data.filename != "README.TXT"]

In [11]:
news_data[news_data.filename == "README.TXT"].count()

category    0
filename    0
text        0
dtype: int64

In [12]:
news_data.text.isnull().sum()

np.int64(0)

### text cleaning

In [13]:
def clean_text(text):
    # 1. Remove HTML tags
    text = re.sub(r'<[^>]*>', '', text)

    # 2. Remove URLs / Hyperlinks
    text = re.sub(r'https?://\S+|www\.\S+', '', text)

    # 3. Remove Email addresses
    text = re.sub(r'\S+@\S+', '', text)

    # 4. Remove everything except letters and numbers (keeps spaces)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

    # 5. Remove numbers/digits
    text = re.sub(r'\d+', '', text)

    # 6. Replace multiple spaces/newlines with a single space
    text = re.sub(r'\s+', ' ', text)

    # 7. Strip leading and trailing whitespace and lowercase
    return text.strip().lower()

In [14]:
news_data['clean_text'] = news_data['text'].apply(lambda x: clean_text(x))

In [15]:
news_data.head(1)['clean_text'].tolist()

['budget to set scene for election gordon brown will seek to put the economy at the centre of labours bid for a third term in power when he delivers his ninth budget at gmt he is expected to stress the importance of continued economic stability with low unemployment and interest rates the chancellor is expected to freeze petrol duty and raise the stamp duty threshold from but the conservatives and lib dems insist voters face higher taxes and more meanstesting under labour treasury officials have said there will not be a preelection giveaway but mr brown is thought to have about bn to spare increase in the stamp duty threshold from a freeze on petrol duty an extension of tax credit scheme for poorer families possible help for pensioners the stamp duty threshold rise is intended to help first time buyers a likely theme of all three of the main parties general election manifestos ten years ago buyers had a much greater chance of avoiding stamp duty with close to half a million properties in england and wales alone selling for less than since then average uk property prices have more than doubled while the starting threshold for stamp duty has not increased tax credits as a result the number of properties incurring stamp duty has rocketed as has the governments tax take the liberal democrats unveiled their own proposals to raise the stamp duty threshold to in february the tories are also thought likely to propose increased thresholds with shadow chancellor oliver letwin branding stamp duty a classic labour stealth tax the tories say whatever the chancellor gives away will be clawed back in higher taxes if labour is returned to power shadow treasury chief secretary george osborne said everyone who looks at the british economy at the moment says there has been a sharp deterioration in the public finances that there is a black hole he said if labour is elected there will be a very substantial tax increase in the budget after the election of the order of around bn but mr browns former advisor ed balls now a parliamentary hopeful said an examination of tory plans for the economy showed there would be a bn difference in investment by the end of the next parliament between the two main parties he added i dont accept there is any need for any changes to the plans we have set out to meet our spending commitments for the lib dems david laws said the chancellor will no doubt tell us today how wonderfully the economy is doing he said but a lot of that is built on an increase in personal and consumer debt over the last few years that makes the economy quite vulnerable potentially if interest rates ever do have to go up in a significant way snp leader alex salmond said his party would introduce a grant for first time buyers reduce corporation tax and introduce a citizens pension free from means testing plaid cymrus economics spokesman adam price said he wanted help to get people on the housing ladder and an increase in the minimum wage to an hour']

### remove stopwords

In [16]:
stop_words = set(stopwords.words('english'))

In [17]:
custom_stopwords = {
    "said", "would", "could", "also",
    "say", "told", "one", "new",
    "year", "years", "week",
    "last", "next", "may",
    "make", "made", "added",
    "bbc", "people", "time"
}

In [18]:
news_data['clean_text']= news_data['clean_text'].apply(lambda x: ' '.join(word for word in x.split() if word not in stop_words))

In [19]:
news_data['clean_text'] = news_data['clean_text'].apply(lambda x: ' '.join(word for word in x.split() if word not in custom_stopwords))

### removing short words

In [20]:
news_data['important_text'] = news_data['clean_text'].apply(lambda x: ' '.join(word for word in x.split() if len(word) > 2))

In [21]:
news_data['important_text'].head(1).tolist()

['budget set scene election gordon brown seek put economy centre labours bid third term power delivers ninth budget gmt expected stress importance continued economic stability low unemployment interest rates chancellor expected freeze petrol duty raise stamp duty threshold conservatives lib dems insist voters face higher taxes meanstesting labour treasury officials preelection giveaway brown thought spare increase stamp duty threshold freeze petrol duty extension tax credit scheme poorer families possible help pensioners stamp duty threshold rise intended help first buyers likely theme three main parties general election manifestos ten ago buyers much greater chance avoiding stamp duty close half million properties england wales alone selling less since average property prices doubled starting threshold stamp duty increased tax credits result number properties incurring stamp duty rocketed governments tax take liberal democrats unveiled proposals raise stamp duty threshold february tories thought likely propose increased thresholds shadow chancellor oliver letwin branding stamp duty classic labour stealth tax tories whatever chancellor gives away clawed back higher taxes labour returned power shadow treasury chief secretary george osborne everyone looks british economy moment says sharp deterioration public finances black hole labour elected substantial tax increase budget election order around browns former advisor balls parliamentary hopeful examination tory plans economy showed difference investment end parliament two main parties dont accept need changes plans set meet spending commitments lib dems david laws chancellor doubt tell today wonderfully economy lot built increase personal consumer debt makes economy quite vulnerable potentially interest rates ever significant way snp leader alex salmond party introduce grant first buyers reduce corporation tax introduce citizens pension free means testing plaid cymrus economics spokesman adam price wanted help get housing ladder increase minimum wage hour']

# 3. Lemmetization

In [23]:
lemmatizer = WordNetLemmatizer()

news_data['lemme'] = news_data['important_text'].apply(
    lambda x: ' '.join(
        lemmatizer.lemmatize(word)
        for word in x.split()
    )
)

# 4. Doc2Vec

In [26]:
from gensim.models.doc2vec import TaggedDocument

documents = [
    TaggedDocument(
        words=text.split(),
        tags=[str(i)]
    )
    for i, text in enumerate(news_data["lemme"])
]

In [30]:
model = Doc2Vec(
    documents,
    vector_size=100,
    window=5,
    min_count=3,
    dm=1,
    epochs=30,
    workers=4
)

In [31]:
doc_vectors = np.array([
    model.dv[str(i)]
    for i in range(len(documents))
])

In [32]:
print(doc_vectors.shape)

(2225, 100)

### finding cosine similarity

In [33]:
# finding cosine similarity

from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(
    [doc_vectors[1]],
    doc_vectors
)

In [35]:
similarities.argsort()[0][-10:]

array([171,  81, 261,   9, 296, 189,  56, 126, 329,   1])

In [38]:
list_last_10 = similarities.argsort()[0][-10:]

for i in list_last_10:
    print(f"{i} : Domain: {news_data.iloc[i]['category']} & {news_data.iloc[i]['text']}")

171 : Domain: politics & Police chief backs drinking move

A chief constable has backed the introduction of 24-drinking, saying police had a responsibility to ensure people could benefit from a law change.

However, Norfolk police chief Andy Hayman also warned that a great deal of preparatory work was still needed. "I don't subscribe to the views of some of my colleagues who are coming out and objecting to it," he said. His comments come after the Liberal Democrats backed Tory demands that the government's plans be put on hold. Andy Hayman said he did not agree with politicians and senior police officers who have objected to the plans, which come into force on 7 February. "I feel that is a premature position to be taking," he said. Among those who have criticised the plans are the UK's top policeman Sir John Stevens.

The Metropolitan police chief said last week that the plans for 24-hour drinking should be re-examined because of a binge drinking "epidemic". However, Mr Hayman said: "It would be totally unacceptable in my view for a chief constable to say, 'I'm very sorry'. He said that police should make sure that responsible people who wanted a change could benefit from more liberal legislation. "My view is that I have got a responsibility to create an environment where that can happen, " he said. However, he believes a lot of preparatory work is still needed to be done by police, local authorities and the drinks industry before the nation was ready for 24-hour drinking. But he is confident problems in the early days can be "ironed out". He believed the majority of people favoured this law change and "we have to accept that lifestyles are changing". But aspects such as transport, and basic things such as making sure public toilets are open all night had to be taken into account.

Prime Minister Tony Blair has defended the Licensing Act, saying it is wrong to deny people the relaxed hours enjoyed elsewhere in Europe because of a "tiny minority" of violent binge drinkers. A six-month transitional period starts on 7 February during which time venues can apply for extended licences. The Conservatives have called for 24-hour drinking to be shelved until the problems of binge drinking are solved. On Monday, the Lib Dems also called for a delay. Lib Dem Home Affairs spokesman Mark Oaten said: "It would clearly be prudent to allow the police and local authorities more time to prepare for flexible drinking hours." Chief constable Mr Hayman acknowledged that binge drinking did cause problems. "If you come to Norwich on a Friday or Saturday night you will see things going on that will you make you feel ashamed. "However, I want industry to succeed in Norwich and I want Norwich to be the recognised nightspot of East Anglia. "There is no way I want to say we cannot manage it or police it. We can."

81 : Domain: politics & Boateng to step down at election

Paul Boateng, Chief Secretary to the Treasury, is to step down as a Labour MP at the forthcoming general election.

Mr Boateng, 53, is to become the UK's high commissioner to South Africa. He was the UK's first black cabinet minister when appointed to his post in 2002, promoted from the Home Office, where he had been prisons minister. Mr Boateng served on the Greater London Council before being elected to Parliament in 1987, declaring "today Brent South, tomorrow Soweto". He will succeed the previous High Commissioner, Ann Grant, shortly after the next election, which is widely expected to be held on 5 May. The appointment is dependent on Labour's re-election.

Prime Minister Tony Blair said: "Paul has been both a valued colleague and a trusted friend for many years. "He has made an immense contribution to public life in Britain and I am delighted that he has agreed to continue that service to the people of Britain by acting as their representative in South Africa." Chancellor Gordon Brown said: "Over the past eight years Paul's contribution to the Treasury and the government has been exceptional - and it has been my privilege to have worked closely with him closely at the Treasury. "I congratulate Paul on his new appointment. "He has displayed huge dedication to the cause of African development for many years and it is fitting that, in this year of challenge and opportunity for the African continent, Paul has been given such a pivotal role in our fight against poverty and injustice. "I look forward to continuing to work with Paul on this vital agenda."

Mr Boateng said: "I am honoured to be asked to take on this role, especially as it comes at such an integral time for our relationship with South Africa and the African continent. "There shall be many new challenges and opportunities ahead and I look forward to embracing them with great anticipation." Asked if he was appointed as the result of a "fair and open" competition, he replied: "I have been appointed as a result of a process that's been used before by Labour and Conservative governments to appoint people of all parties who have relevant experience." Mr Boateng also laughed off suggestions that his re-election in Brent South seat had been in danger saying it was "one of the safest Labour seats in the country". Shadow foreign secretary Michael Ancram said that, if in government, he would refuse to approve either Mr Boateng's appointment or that of ex-Cabinet minister Helen Liddell as high commissioner to Australia. "Mr Blair's appointment of Paul Boateng is the latest example of a worrying trend of failed Tony's cronies being appointed to senior diplomatic posts," he said.

261 : Domain: politics & Stalemate in pension strike talks

Talks aimed at averting national strikes over pension reforms have ended without agreement after 90 minutes.

Five public sector unions met Deputy Prime Minister John Prescott at the Labour spring conference in Gateshead. They want the government to withdraw regulations - due to be introduced in weeks - which would raise the pension age for council workers from 60 to 65. Up to 1.4 million workers could take part in strikes earmarked for 23 March. Discussions will resume next week.

A spokesman for Unison, Britain's biggest union, said after Saturday's meeting: "At least we are still talking." All sides are anxious to avoid a major confrontation in the run up to the general election, said BBC labour affairs correspondent Stephen Cape. In four days, Unison will start balloting 800,000 local government workers on strikes. Other public sector unions have pledged to follow. The five unions which met Mr Prescott want the government to withdraw these regulations. This would allow months of tough negotiations to follow, said our correspondent. But a spokesman for Mr Prescott warned that the changes to the local government pension scheme would have to go ahead in April.

Privately ministers believe this will be the "less painful" option, our correspondent added. The Public and Commercial Services Union (PCS) will co-ordinate any industrial action with up to six other public sector unions. PCS leader Mark Serwotka warned last week that there could be further walkouts unless there was a government rethink. "For a government that lectures everyone on choice - choice on public service, choice on this and choice on that - isn't it ironic that they're saying to public sector workers there is no choice," he said. "If you want the pension you were promised when you started you must work for an extra five years - that is working until people drop. "In the 20th century, it's completely unacceptable."

Unison's 800,000 workers, the Transport and General Workers' Union's 70,000 and Amicus' 20,000 are among those being balloted about a 23 March walkout. Mr Prescott held a private meeting with senior union figures last week. It is understood no deal was offered in that meeting but there was room for further negotiations.

9 : Domain: politics & Tories unveil quango blitz plans

Plans to abolish 162 quangos have been unveiled by the Conservatives as part of their effort to show how government red tape can be cut.

Six government units would also be scrapped under proposals which the Tories say would save more than Â£4.3bn. Among the targets are strategic health authorities and the new fair access regulator for universities. Tory frontbencher John Redwood said Britain needed a slimmer government and lower taxes to be competitive.

The plans would abolish regional assemblies and other regional bodies, such as boards tackling industrial development and housing. Their powers would be returned to elected local councils or national government. The Tories say the strategic health authorities are not needed as it is better that local people, rather than officials, run hospitals and surgeries.

Announcing the plans, Mr Redwood said: "Mr Blair has forgotten the interests of taxpayers, and has broken the pledges he made. "Far from improving public services, spending taxpayers' money on quangos has led only to more bureaucrats, more regulation and higher taxes." His party leader, Michael Howard, argued a change in direction was needed to get a grip on spending. "Labour are creating Two Britains: the Britain of the forgotten majority and bureaucratic Britain," he said. "In the real world, people are working harder just to stand still. They've seen their pensions knocked for six. "They're being squeezed by extra taxes. The forgotten majority are paying the price of bureaucratic Britain."

The government has announced plans to cut 100,000 civil servants as part of its efficiency drive. But Chief Secretary to the Treasury Paul Boateng attacked the Tory plans. "The Conservatives are committed to cutting Labour's public spending plans by a massive Â£35 billion," he said. "Cuts on this scale cannot be found from cutting 'bureaucracy' but would require massive cuts to front-line public services such as schools, hospitals and the police." The Liberal Democrats have said they would cut the number of Whitehall departments to make sure money reaches frontline services.

296 : Domain: politics & Talks aim to avert pension strike

Talks aimed at averting a series of national strikes over pensions reforms will take place this weekend.

Five public sector unions will hold private talks with Deputy Prime Minister John Prescott at Labour's spring conference in Gateshead. They want the government to withdraw regulations - due to be introduced in weeks - which would raise the pension age for council workers from 60 to 65. Up to 1.4m workers could take part in a strike already earmarked for 23 March. However, all sides are anxious to avoid a major confrontation in the run up to the general election, said BBC labour affairs correspondent Stephen Cape. In four days, Britain's biggest union Unison will start balloting 800,000 local government workers on strikes. Other public sector unions have pledged to follow. It is just weeks before new regulations are introduced to raise the pension age of local government workers.

The five unions meeting Mr Prescott want the government to withdraw these regulations. This would allow months of tough negotiations to follow, said our correspondent. But a spokesman for Mr Prescott warned that the changes to the local government pension scheme would have to go ahead in April. Privately ministers believe this will be the "less painful" option, our correspondent added. The Public and Commercial Services Union (PCS) will co-ordinate any industrial action with up to six other public sector unions. PCS leader Mark Serwotka warned last week that there could be further walkouts unless there was a government rethink. "For a government that lectures everyone on choice - choice on public service, choice on this and choice on that - isn't it ironic that they're saying to public sector workers there is no choice," he said. "If you want the pension you were promised when you started you must work for an extra five years - that is working until people drop. "In the 20th century, it's completely unacceptable."

Unison's 800,000 workers, the Transport and General Workers' Union's 70,000 and Amicus' 20,000 are among those being balloted about a 23 March walkout. Mr Prescott held a private meeting with senior union figures last week. It is understood no deal was offered in that meeting but there was room for further negotiations.

189 : Domain: politics & Councils prepare to set tax rises

Council tax in Scotland is set to rise by an average of about 4% in the coming year, BBC Scotland has learned.

Authorities will decide final figures on Thursday when projected increases will be more than twice the rate of inflation, which is currently 1.6%. The finance minister has urged councils to limit increases but they have warned that they will struggle to maintain services unless funding is increased. They say much additional government money is for new initiatives. Scottish Finance Minister, Tom McCabe MSP, said: "Last week in parliament I announced an additional Â£419m for core expenditure to local government in Scotland. "That's a 5.5% increase and sits against an inflation rate of 1.6%, so I think we have quite rightly said to councils this year that we would at the very least ask them to exercise restraint." Mr McCabe is also looking for local authorities to become more efficient and save money in coming years. He told BBC Radio Scotland's Sunday Live programme: "Here in Scotland we have 32 councils who all have their own individual collection systems for council tax, they have their own payroll systems and their own human resource systems.

"We think there has to be opportunities there for rationalisation and using the money saved to reinvest in frontline services." The councils' umbrella organisation Cosla, which provided BBC Scotland with the indicative figures for next year, warned that councils would face a continuous struggle to maintain services. Mr McCabe has promised them about Â£8.1bn next year. "However, most of the increase is targeted to new initiatives and councils will experience difficulties in maintaining core services," a Cosla spokesman said. Cosla says that it is willing to work with the executive on finding efficiency savings but that these will not be enough to maintain services. They say the funding plans for the next three years will see councils lose more of the share of public spending. The Conservatives accuse the Scottish Executive of using the council tax to raise funds because it is too afraid to raise income tax.

The Tory finance spokesman, Brian Monteith MSP, said: "Its a form of disguise... yet again we see that council tax is being used as a way of passing on costs. "Scared of actually using its three pence income tax that it could put up, what we've seen over the years is more and more burdens being put onto local authorities and the council tax payer having to pick up the bill." There are also warnings that unless funding to councils is increased in the next few years then services may have to be reduced. Linda Knox, Director of the Scottish Local Authority Management Centre at Strathclyde University, said: "With this current settlement the increase is slowing. At the same time, the burdens on councils are greater than they were. "The settlement figures don't include pay increases and the executive is also requiring a substantial figure - in the area of Â£325m - in efficiency savings across the settlement period." Education will be protected from any cuts but Linda Knox says this will mean other services will suffer. She said: "In practice, that will mean a 4-5% cut for other services. On the face of it the settlement looks like an increase of about 9.7% but by the time you take into account other factors its probably only about 1% in real terms."

56 : Domain: politics & Crucial decision on super-casinos

A decision on whether to allow Westminster to legislate on super-casinos is set to be made by the Scottish Parliament.

The government has plans for up to eight Las Vegas style resorts in the UK, one of which is likely to be in Glasgow. Scottish ministers insist they will still have the final say on whether a super-casino will be built in Scotland. But opposition parties say that will not happen in practice. The vote is due to be taken on Wednesday and is expected to be close.

The Scottish Executive believes that the legislation should be handled by Westminster. The new law will control internet gambling for the first time and is aimed at preventing children from becoming involved. A super-casino in Glasgow could be located at Ibrox or the Scottish Exhibition and Conference Centre. The new gambling bill going through Westminster will allow casino complexes to open to the public, have live entertainment and large numbers of fruit machines with unlimited prizes. But the Scottish National Party and the Tories say the issue of super-casinos should be decided in Scotland and believe the executive is shirking its responsibility.

126 : Domain: politics & Tories outlining policing plans

Local communities would be asked to go to the polls to elect their own area police commissioner, under plans unveiled by the Conservatives.

Party leader Michael Howard said the new role would replace "inconspicuous" police authorities. He said the new office would not supersede the job of a chief constable. The Lib Dems said the plan could let extreme groups run policing, while Labour criticised "extravagant" Tory promises on policing.

Responding to the plans, the chairman of the Police Federation of England and Wales, which represents rank and file officers, said it was essential operational independence was retained.

Jan Berry said: "It is a service, not a political football to be kicked around every time an election approaches. "These plans could result in those with extreme political views dictating what actually happens on the ground," she warned. Outlining his crime manifesto, Mr Howard said elected police commissioners would be more accountable than police authorities which are made up of local councillors and magistrates. "The commissioner will have the powers which existing police authorities have," he told BBC Radio 4's Today programme. "The trouble is, and it's no reflection on the people who are on the police authority - they are good people - but hardly anyone knows who they are." Mr Howard said the authorities were not "providing the local accountability that we want to see" and that elected police commissioners would be more visible.

Critics fear the move could hand control of the police to single-issue campaigners who would ignore the needs of the wider community. Lord Harris, who sits on the executive of Association of Police Authorities, said the plans seemed to suggest chief constables should be told what to do by a single politician. "That is overturning nearly 200 years of the way in which we have organised policing in this country to avoid the politicisation of policing decisions," he said.

Liberal Democrat home affairs spokesman Mark Oaten said the plan was dangerous and "could create conflict between chief constables and elected officials". Mr Oaten said local people had too little control over policing but a far better solution would be for elected councillors to draw up a "minimum policing guarantee" with their chief constables. A Labour Party spokesman criticised Michael Howard's record, saying police numbers had fallen by 1,132 when he was home secretary. He said: "Today the Tories are making more extravagant promises on the police without making clear how they would pay for them, other than through fantasy savings to the asylum system." The Tories insists the commissioner role would not be like that of an American sheriff. Other Tory law and order plans include building more prisons and making criminals serve full jail sentences.

329 : Domain: politics & Regiments' group in poll move

A regiments' campaign group is to target nine marginal Labour seats at the General Election.


sounds well distributed

# 5,6. K-means & Silhuette score

In [43]:
for k in range(2, 11):
  k_means = KMeans(
      n_clusters = k,
      random_state = 42,
      n_init = 10
  )

  labels = k_means.fit_predict(doc_vectors)

  score = silhouette_score(doc_vectors, labels)
  print(f"Silhouette Score for k={k}: {score}")

Silhouette Score for k=2: 0.06764724850654602
Silhouette Score for k=3: 0.06705082207918167
Silhouette Score for k=4: 0.05758701264858246
Silhouette Score for k=5: 0.052891504019498825
Silhouette Score for k=6: 0.05591220036149025
Silhouette Score for k=7: 0.0631881058216095
Silhouette Score for k=8: 0.04562464728951454
Silhouette Score for k=9: 0.049535948783159256
Silhouette Score for k=10: 0.044707100838422775

# 7. Conclusion

On the BBC News corpus (~2200 documents), Word2Vec with mean-pooled document embeddings substantially outperformed Doc2Vec for unsupervised clustering.