# Loading Data

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("shivamkushwaha/bbc-full-text-document-classification")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/shivamkushwaha/bbc-full-text-document-classification/1.archive...

100%|██████████| 5.59M/5.59M [00:00<00:00, 73.9MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/shivamkushwaha/bbc-full-text-document-classification/versions/1

# Import Necessary Dependencies

In [2]:
import numpy as np
import pandas as pd

# Convert Text Data to CSV

In [3]:
# show folders from this path : /root/.cache/kagglehub/datasets/shivamkushwaha/bbc-full-text-document-classification/versions/1
import os
for dirname in os.walk('/root/.cache/kagglehub/datasets/shivamkushwaha/bbc-full-text-document-classification/versions/1'):
        print(dirname)

('/root/.cache/kagglehub/datasets/shivamkushwaha/bbc-full-text-document-classification/versions/1', ['bbc-fulltext (document classification)', 'bbc'], [])
('/root/.cache/kagglehub/datasets/shivamkushwaha/bbc-full-text-document-classification/versions/1/bbc-fulltext (document classification)', ['bbc'], [])
('/root/.cache/kagglehub/datasets/shivamkushwaha/bbc-full-text-document-classification/versions/1/bbc-fulltext (document classification)/bbc', ['business', 'sport', 'politics', 'entertainment', 'tech'], ['README.TXT'])
('/root/.cache/kagglehub/datasets/shivamkushwaha/bbc-full-text-document-classification/versions/1/bbc-fulltext (document classification)/bbc/business', [], ['412.txt', '311.txt', '365.txt', '107.txt', '304.txt', '110.txt', '020.txt', '482.txt', '320.txt', '508.txt', '220.txt', '054.txt', '441.txt', '028.txt', '378.txt', '323.txt', '192.txt', '001.txt', '427.txt', '421.txt', '084.txt', '219.txt', '339.txt', '356.txt', '341.txt', '437.txt', '343.txt', '058.txt', '353.txt', '138.txt', '073.txt', '350.txt', '268.txt', '357.txt', '184.txt', '185.txt', '172.txt', '271.txt', '485.txt', '166.txt', '453.txt', '178.txt', '072.txt', '498.txt', '473.txt', '080.txt', '159.txt', '252.txt', '244.txt', '063.txt', '154.txt', '182.txt', '258.txt', '499.txt', '129.txt', '269.txt', '500.txt', '139.txt', '188.txt', '117.txt', '364.txt', '167.txt', '051.txt', '276.txt', '486.txt', '096.txt', '358.txt', '248.txt', '179.txt', '301.txt', '226.txt', '078.txt', '487.txt', '444.txt', '189.txt', '232.txt', '025.txt', '039.txt', '270.txt', '495.txt', '015.txt', '228.txt', '164.txt', '125.txt', '287.txt', '264.txt', '074.txt', '079.txt', '157.txt', '305.txt', '130.txt', '194.txt', '283.txt', '207.txt', '209.txt', '295.txt', '029.txt', '380.txt', '503.txt', '443.txt', '293.txt', '296.txt', '068.txt', '021.txt', '402.txt', '480.txt', '204.txt', '312.txt', '221.txt', '211.txt', '134.txt', '321.txt', '095.txt', '435.txt', '103.txt', '018.txt', '124.txt', '483.txt', '190.txt', '292.txt', '147.txt', '509.txt', '146.txt', '186.txt', '464.txt', '387.txt', '400.txt', '329.txt', '422.txt', '344.txt', '216.txt', '423.txt', '438.txt', '319.txt', '035.txt', '416.txt', '475.txt', '367.txt', '488.txt', '408.txt', '436.txt', '255.txt', '128.txt', '118.txt', '351.txt', '246.txt', '403.txt', '160.txt', '491.txt', '262.txt', '013.txt', '041.txt', '440.txt', '257.txt', '272.txt', '374.txt', '369.txt', '126.txt', '419.txt', '156.txt', '497.txt', '144.txt', '316.txt', '313.txt', '008.txt', '168.txt', '454.txt', '415.txt', '060.txt', '036.txt', '375.txt', '336.txt', '224.txt', '007.txt', '111.txt', '137.txt', '502.txt', '108.txt', '510.txt', '263.txt', '411.txt', '462.txt', '413.txt', '291.txt', '119.txt', '236.txt', '086.txt', '067.txt', '143.txt', '055.txt', '259.txt', '294.txt', '432.txt', '212.txt', '155.txt', '322.txt', '012.txt', '379.txt', '064.txt', '371.txt', '281.txt', '003.txt', '382.txt', '140.txt', '075.txt', '448.txt', '057.txt', '501.txt', '300.txt', '338.txt', '496.txt', '066.txt', '325.txt', '418.txt', '332.txt', '463.txt', '062.txt', '484.txt', '231.txt', '048.txt', '254.txt', '452.txt', '481.txt', '069.txt', '474.txt', '349.txt', '445.txt', '250.txt', '038.txt', '424.txt', '045.txt', '363.txt', '142.txt', '314.txt', '152.txt', '384.txt', '158.txt', '011.txt', '101.txt', '195.txt', '354.txt', '109.txt', '171.txt', '431.txt', '088.txt', '409.txt', '395.txt', '460.txt', '121.txt', '278.txt', '451.txt', '370.txt', '170.txt', '273.txt', '076.txt', '243.txt', '433.txt', '315.txt', '327.txt', '493.txt', '120.txt', '010.txt', '056.txt', '471.txt', '091.txt', '229.txt', '239.txt', '466.txt', '290.txt', '230.txt', '399.txt', '208.txt', '148.txt', '165.txt', '215.txt', '145.txt', '392.txt', '468.txt', '123.txt', '006.txt', '347.txt', '169.txt', '359.txt', '506.txt', '046.txt', '032.txt', '456.txt', '397.txt', '429.txt', '361.txt', '340.txt', '114.txt', '127.txt', '277.txt', '053.txt', '279.txt', '266.txt', '191.txt', '071.txt', '289.txt', '335.txt', '267.txt', '203.txt', '253.txt', '135.txt', '162.txt', '285.txt', '330.txt', '177.txt', '390.txt', '458.txt', '428.txt', '446.txt', '153.txt', '430.txt', '317.txt', '507.txt', '136.txt', '394.txt', '225.txt', '217.txt', '288.txt', '197.txt', '040.txt', '377.txt', '405.txt', '214.txt', '163.txt', '193.txt', '302.txt', '047.txt', '052.txt', '308.txt', '299.txt', '256.txt', '202.txt', '196.txt', '245.txt', '284.txt', '333.txt', '366.txt', '070.txt', '049.txt', '089.txt', '181.txt', '104.txt', '105.txt', '019.txt', '131.txt', '450.txt', '261.txt', '334.txt', '324.txt', '027.txt', '175.txt', '393.txt', '004.txt', '274.txt', '218.txt', '183.txt', '235.txt', '386.txt', '373.txt', '465.txt', '044.txt', '241.txt', '337.txt', '115.txt', '477.txt', '242.txt', '050.txt', '023.txt', '449.txt', '447.txt', '173.txt', '326.txt', '286.txt', '381.txt', '133.txt', '426.txt', '093.txt', '442.txt', '141.txt', '002.txt', '457.txt', '176.txt', '085.txt', '034.txt', '024.txt', '396.txt', '342.txt', '251.txt', '210.txt', '404.txt', '328.txt', '112.txt', '494.txt', '260.txt', '234.txt', '205.txt', '199.txt', '280.txt', '161.txt', '372.txt', '489.txt', '504.txt', '479.txt', '467.txt', '249.txt', '187.txt', '151.txt', '043.txt', '014.txt', '094.txt', '348.txt', '478.txt', '017.txt', '026.txt', '391.txt', '360.txt', '042.txt', '346.txt', '030.txt', '420.txt', '180.txt', '200.txt', '081.txt', '102.txt', '401.txt', '238.txt', '097.txt', '149.txt', '492.txt', '090.txt', '383.txt', '201.txt', '425.txt', '406.txt', '352.txt', '376.txt', '345.txt', '461.txt', '122.txt', '099.txt', '005.txt', '298.txt', '297.txt', '247.txt', '306.txt', '414.txt', '398.txt', '310.txt', '206.txt', '455.txt', '233.txt', '469.txt', '031.txt', '227.txt', '265.txt', '434.txt', '362.txt', '009.txt', '222.txt', '410.txt', '016.txt', '022.txt', '309.txt', '083.txt', '037.txt', '061.txt', '198.txt', '318.txt', '113.txt', '490.txt', '092.txt', '505.txt', '389.txt', '106.txt', '417.txt', '368.txt', '237.txt', '355.txt', '132.txt', '472.txt', '098.txt', '087.txt', '307.txt', '150.txt', '385.txt', '275.txt', '174.txt', '282.txt', '331.txt', '033.txt', '439.txt', '059.txt', '407.txt', '459.txt', '213.txt', '476.txt', '240.txt', '470.txt', '303.txt', '082.txt', '116.txt', '065.txt', '100.txt', '223.txt', '077.txt', '388.txt'])
('/root/.cache/kagglehub/datasets/shivamkushwaha/bbc-full-text-document-classification/versions/1/bbc-fulltext (document classification)/bbc/sport', [], ['412.txt', '311.txt', '365.txt', '107.txt', '304.txt', '110.txt', '020.txt', '482.txt', '320.txt', '508.txt', '220.txt', '054.txt', '441.txt', '028.txt', '378.txt', '323.txt', '192.txt', '001.txt', '427.txt', '421.txt', '084.txt', '219.txt', '339.txt', '356.txt', '341.txt', '437.txt', '343.txt', '058.txt', '353.txt', '138.txt', '073.txt', '350.txt', '268.txt', '357.txt', '184.txt', '185.txt', '172.txt', '271.txt', '485.txt', '166.txt', '453.txt', '178.txt', '072.txt', '498.txt', '473.txt', '080.txt', '159.txt', '252.txt', '244.txt', '063.txt', '154.txt', '182.txt', '258.txt', '499.txt', '129.txt', '269.txt', '500.txt', '139.txt', '188.txt', '117.txt', '364.txt', '167.txt', '051.txt', '276.txt', '486.txt', '096.txt', '358.txt', '248.txt', '179.txt', '301.txt', '226.txt', '078.txt', '487.txt', '444.txt', '189.txt', '232.txt', '025.txt', '039.txt', '270.txt', '495.txt', '015.txt', '228.txt', '164.txt', '125.txt', '287.txt', '264.txt', '074.txt', '079.txt', '157.txt', '305.txt', '130.txt', '194.txt', '283.txt', '207.txt', '209.txt', '295.txt', '029.txt', '380.txt', '503.txt', '443.txt', '293.txt', '296.txt', '068.txt', '021.txt', '402.txt', '480.txt', '204.txt', '312.txt', '221.txt', '211.txt', '134.txt', '321.txt', '095.txt', '435.txt', '103.txt', '018.txt', '124.txt', '483.txt', '190.txt', '292.txt', '147.txt', '509.txt', '146.txt', '186.txt', '464.txt', '387.txt', '400.txt', '329.txt', '422.txt', '344.txt', '216.txt', '423.txt', '438.txt', '319.txt', '035.txt', '416.txt', '475.txt', '367.txt', '488.txt', '408.txt', '436.txt', '255.txt', '128.txt', '118.txt', '351.txt', '246.txt', '403.txt', '160.txt', '491.txt', '262.txt', '013.txt', '041.txt', '440.txt', '257.txt', '272.txt', '374.txt', '369.txt', '126.txt', '419.txt', '156.txt', '497.txt', '144.txt', '316.txt', '313.txt', '008.txt', '168.txt', '454.txt', '415.txt', '060.txt', '036.txt', '375.txt', '336.txt', '224.txt', '007.txt', '111.txt', '137.txt', '502.txt', '108.txt', '510.txt', '263.txt', '411.txt', '462.txt', '413.txt', '291.txt', '119.txt', '236.txt', '086.txt', '067.txt', '143.txt', '055.txt', '259.txt', '294.txt', '432.txt', '212.txt', '155.txt', '322.txt', '012.txt', '379.txt', '064.txt', '371.txt', '281.txt', '003.txt', '382.txt', '140.txt', '075.txt', '448.txt', '057.txt', '501.txt', '300.txt', '338.txt', '496.txt', '066.txt', '325.txt', '418.txt', '332.txt', '463.txt', '062.txt', '484.txt', '231.txt', '048.txt', '254.txt', '452.txt', '481.txt', '069.txt', '474.txt', '349.txt', '445.txt', '250.txt', '038.txt', '424.txt', '045.txt', '363.txt', '142.txt', '314.txt', '152.txt', '384.txt', '158.txt', '011.txt', '101.txt', '195.txt', '354.txt', '109.txt', '171.txt', '431.txt', '088.txt', '409.txt', '395.txt', '460.txt', '121.txt', '278.txt', '451.txt', '370.txt', '170.txt', '273.txt', '076.txt', '243.txt', '433.txt', '315.txt', '327.txt', '493.txt', '120.txt', '010.txt', '056.txt', '471.txt', '091.txt', '229.txt', '239.txt', '466.txt', '290.txt', '230.txt', '399.txt', '208.txt', '148.txt', '165.txt', '215.txt', '145.txt', '392.txt', '468.txt', '123.txt', '006.txt', '347.txt', '169.txt', '359.txt', '506.txt', '046.txt', '032.txt', '456.txt', '397.txt', '429.txt', '361.txt', '340.txt', '114.txt', '127.txt', '277.txt', '053.txt', '279.txt', '266.txt', '191.txt', '071.txt', '289.txt', '335.txt', '267.txt', '203.txt', '253.txt', '135.txt', '162.txt', '285.txt', '330.txt', '177.txt', '390.txt', '458.txt', '428.txt', '446.txt', '153.txt', '430.txt', '317.txt', '507.txt', '136.txt', '394.txt', '225.txt', '217.txt', '288.txt', '197.txt', '040.txt', '377.txt', '405.txt', '214.txt', '163.txt', '193.txt', '302.txt', '047.txt', '052.txt', '308.txt', '299.txt', '256.txt', '202.txt', '511.txt', '196.txt', '245.txt', '284.txt', '333.txt', '366.txt', '070.txt', '049.txt', '089.txt', '181.txt', '104.txt', '105.txt', '019.txt', '131.txt', '450.txt', '261.txt', '334.txt', '324.txt', '027.txt', '175.txt', '393.txt', '004.txt', '274.txt', '218.txt', '183.txt', '235.txt', '386.txt', '373.txt', '465.txt', '044.txt', '241.txt', '337.txt', '115.txt', '477.txt', '242.txt', '050.txt', '023.txt', '449.txt', '447.txt', '173.txt', '326.txt', '286.txt', '381.txt', '133.txt', '426.txt', '093.txt', '442.txt', '141.txt', '002.txt', '457.txt', '176.txt', '085.txt', '034.txt', '024.txt', '396.txt', '342.txt', '251.txt', '210.txt', '404.txt', '328.txt', '112.txt', '494.txt', '260.txt', '234.txt', '205.txt', '199.txt', '280.txt', '161.txt', '372.txt', '489.txt', '504.txt', '479.txt', '467.txt', '249.txt', '187.txt', '151.txt', '043.txt', '014.txt', '094.txt', '348.txt', '478.txt', '017.txt', '026.txt', '391.txt', '360.txt', '042.txt', '346.txt', '030.txt', '420.txt', '180.txt', '200.txt', '081.txt', '102.txt', '401.txt', '238.txt', '097.txt', '149.txt', '492.txt', '090.txt', '383.txt', '201.txt', '425.txt', '406.txt', '352.txt', '376.txt', '345.txt', '461.txt', '122.txt', '099.txt', '005.txt', '298.txt', '297.txt', '247.txt', '306.txt', '414.txt', '398.txt', '310.txt', '206.txt', '455.txt', '233.txt', '469.txt', '031.txt', '227.txt', '265.txt', '434.txt', '362.txt', '009.txt', '222.txt', '410.txt', '016.txt', '022.txt', '309.txt', '083.txt', '037.txt', '061.txt', '198.txt', '318.txt', '113.txt', '490.txt', '092.txt', '505.txt', '389.txt', '106.txt', '417.txt', '368.txt', '237.txt', '355.txt', '132.txt', '472.txt', '098.txt', '087.txt', '307.txt', '150.txt', '385.txt', '275.txt', '174.txt', '282.txt', '331.txt', '033.txt', '439.txt', '059.txt', '407.txt', '459.txt', '213.txt', '476.txt', '240.txt', '470.txt', '303.txt', '082.txt', '116.txt', '065.txt', '100.txt', '223.txt', '077.txt', '388.txt'])
('/root/.cache/kagglehub/datasets/shivamkushwaha/bbc-full-text-document-classification/versions/1/bbc-fulltext (document classification)/bbc/politics', [], ['412.txt', '311.txt', '365.txt', '107.txt', '304.txt', '110.txt', '020.txt', '320.txt', '220.txt', '054.txt', '028.txt', '378.txt', '323.txt', '192.txt', '001.txt', '084.txt', '219.txt', '339.txt', '356.txt', '341.txt', '343.txt', '058.txt', '353.txt', '138.txt', '073.txt', '350.txt', '268.txt', '357.txt', '184.txt', '185.txt', '172.txt', '271.txt', '166.txt', '178.txt', '072.txt', '080.txt', '159.txt', '252.txt', '244.txt', '063.txt', '154.txt', '182.txt', '258.txt', '129.txt', '269.txt', '139.txt', '188.txt', '117.txt', '364.txt', '167.txt', '051.txt', '276.txt', '096.txt', '358.txt', '248.txt', '179.txt', '301.txt', '226.txt', '078.txt', '189.txt', '232.txt', '025.txt', '039.txt', '270.txt', '015.txt', '228.txt', '164.txt', '125.txt', '287.txt', '264.txt', '074.txt', '079.txt', '157.txt', '305.txt', '130.txt', '194.txt', '283.txt', '207.txt', '209.txt', '295.txt', '029.txt', '380.txt', '293.txt', '296.txt', '068.txt', '021.txt', '402.txt', '204.txt', '312.txt', '221.txt', '211.txt', '134.txt', '321.txt', '095.txt', '103.txt', '018.txt', '124.txt', '190.txt', '292.txt', '147.txt', '146.txt', '186.txt', '387.txt', '400.txt', '329.txt', '344.txt', '216.txt', '319.txt', '035.txt', '416.txt', '367.txt', '408.txt', '255.txt', '128.txt', '118.txt', '351.txt', '246.txt', '403.txt', '160.txt', '262.txt', '013.txt', '041.txt', '257.txt', '272.txt', '374.txt', '369.txt', '126.txt', '156.txt', '144.txt', '316.txt', '313.txt', '008.txt', '168.txt', '415.txt', '060.txt', '036.txt', '375.txt', '336.txt', '224.txt', '007.txt', '111.txt', '137.txt', '108.txt', '263.txt', '411.txt', '413.txt', '291.txt', '119.txt', '236.txt', '086.txt', '067.txt', '143.txt', '055.txt', '259.txt', '294.txt', '212.txt', '155.txt', '322.txt', '012.txt', '379.txt', '064.txt', '371.txt', '281.txt', '003.txt', '382.txt', '140.txt', '075.txt', '057.txt', '300.txt', '338.txt', '066.txt', '325.txt', '332.txt', '062.txt', '231.txt', '048.txt', '254.txt', '069.txt', '349.txt', '250.txt', '038.txt', '045.txt', '363.txt', '142.txt', '314.txt', '152.txt', '384.txt', '158.txt', '011.txt', '101.txt', '195.txt', '354.txt', '109.txt', '171.txt', '088.txt', '409.txt', '395.txt', '121.txt', '278.txt', '370.txt', '170.txt', '273.txt', '076.txt', '243.txt', '315.txt', '327.txt', '120.txt', '010.txt', '056.txt', '091.txt', '229.txt', '239.txt', '290.txt', '230.txt', '399.txt', '208.txt', '148.txt', '165.txt', '215.txt', '145.txt', '392.txt', '123.txt', '006.txt', '347.txt', '169.txt', '359.txt', '046.txt', '032.txt', '397.txt', '361.txt', '340.txt', '114.txt', '127.txt', '277.txt', '053.txt', '279.txt', '266.txt', '191.txt', '071.txt', '289.txt', '335.txt', '267.txt', '203.txt', '253.txt', '135.txt', '162.txt', '285.txt', '330.txt', '177.txt', '390.txt', '153.txt', '317.txt', '136.txt', '394.txt', '225.txt', '217.txt', '288.txt', '197.txt', '040.txt', '377.txt', '405.txt', '214.txt', '163.txt', '193.txt', '302.txt', '047.txt', '052.txt', '308.txt', '299.txt', '256.txt', '202.txt', '196.txt', '245.txt', '284.txt', '333.txt', '366.txt', '070.txt', '049.txt', '089.txt', '181.txt', '104.txt', '105.txt', '019.txt', '131.txt', '261.txt', '334.txt', '324.txt', '027.txt', '175.txt', '393.txt', '004.txt', '274.txt', '218.txt', '183.txt', '235.txt', '386.txt', '373.txt', '044.txt', '241.txt', '337.txt', '115.txt', '242.txt', '050.txt', '023.txt', '173.txt', '326.txt', '286.txt', '381.txt', '133.txt', '093.txt', '141.txt', '002.txt', '176.txt', '085.txt', '034.txt', '024.txt', '396.txt', '342.txt', '251.txt', '210.txt', '404.txt', '328.txt', '112.txt', '260.txt', '234.txt', '205.txt', '199.txt', '280.txt', '161.txt', '372.txt', '249.txt', '187.txt', '151.txt', '043.txt', '014.txt', '094.txt', '348.txt', '017.txt', '026.txt', '391.txt', '360.txt', '042.txt', '346.txt', '030.txt', '180.txt', '200.txt', '081.txt', '102.txt', '401.txt', '238.txt', '097.txt', '149.txt', '090.txt', '383.txt', '201.txt', '406.txt', '352.txt', '376.txt', '345.txt', '122.txt', '099.txt', '005.txt', '298.txt', '297.txt', '247.txt', '306.txt', '414.txt', '398.txt', '310.txt', '206.txt', '233.txt', '031.txt', '227.txt', '265.txt', '362.txt', '009.txt', '222.txt', '410.txt', '016.txt', '022.txt', '309.txt', '083.txt', '037.txt', '061.txt', '198.txt', '318.txt', '113.txt', '092.txt', '389.txt', '106.txt', '417.txt', '368.txt', '237.txt', '355.txt', '132.txt', '098.txt', '087.txt', '307.txt', '150.txt', '385.txt', '275.txt', '174.txt', '282.txt', '331.txt', '033.txt', '059.txt', '407.txt', '213.txt', '240.txt', '303.txt', '082.txt', '116.txt', '065.txt', '100.txt', '223.txt', '077.txt', '388.txt'])

In [4]:
import os
import pandas as pd

DATASET_PATH = "/root/.cache/kagglehub/datasets/shivamkushwaha/bbc-full-text-document-classification/versions/1/bbc"

rows = []

for category in os.listdir(DATASET_PATH):

    category_path = os.path.join(DATASET_PATH, category)

    if not os.path.isdir(category_path):
        continue

    for file in os.listdir(category_path):

        if not file.endswith(".txt"):
            continue

        file_path = os.path.join(category_path, file)

        try:
            with open(file_path, "r", encoding="latin-1") as f:
                text = f.read()

            rows.append({
                "category": category,
                "filename": file,
                "text": text
            })

        except Exception as e:
            print(f"Error reading {file}: {e}")

df = pd.DataFrame(rows)

print(df.shape)

df.to_csv(
    "bbc_news_dataset.csv",
    index=False
)

print("Saved: bbc_news_dataset.csv")

(2225, 3)
Saved: bbc_news_dataset.csv

In [5]:
news_csv = pd.read_csv("bbc_news_dataset.csv")

In [6]:
news_csv.head(5)

   category filename                                               text
0  business  412.txt  Iran budget seeks state sell-offs\n\nIran's pr...
1  business  311.txt  Stormy year for property insurers\n\nA string ...
2  business  365.txt  Nasdaq planning $100m-share sale\n\nThe owner ...
3  business  107.txt  Liberian economy starts to grow\n\nThe Liberia...
4  business  304.txt  Bombardier chief to leave company\n\nShares in...

In [7]:
pd.unique(df.category)

array(['business', 'sport', 'politics', 'entertainment', 'tech'],
      dtype=object)

# Data PreProcessing

- this step includes, removing null values, duplicated values, text cleaning, stopword removal, lemmetization

#### Null Values

In [8]:
pd.isnull(df.category).sum()

np.int64(0)

In [9]:
pd.isnull(df.filename).sum()

np.int64(0)

In [10]:
pd.isnull(df.text).sum()

np.int64(0)

No null values exists

#### Duplicate Values

In [11]:
df.duplicated().sum()

np.int64(0)

no duplicate rows

### Text cleaning (removing punctuations, numbers & special characters)

In [12]:
import re


def clean_text(text):
    # 1. Remove HTML tags
    text = re.sub(r'<[^>]*>', '', text)

    # 2. Remove URLs / Hyperlinks
    text = re.sub(r'https?://\S+|www\.\S+', '', text)

    # 3. Remove Email addresses
    text = re.sub(r'\S+@\S+', '', text)

    # 4. Remove everything except letters and numbers (keeps spaces)
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

    # 5. Remove numbers/digits
    text = re.sub(r'\d+', '', text)

    # 6. Replace multiple spaces/newlines with a single space
    text = re.sub(r'\s+', ' ', text)

    # 7. Strip leading and trailing whitespace and lowercase
    return text.strip().lower()

In [13]:
news_csv['clean_text'] = news_csv['text'].apply(lambda x: clean_text(x))

In [14]:
news_csv.head(6)

,category,filename,text,clean_text
0,business,412.txt,Iran budget seeks state sell-offs\n\nIran's pr...,iran budget seeks state selloffs irans preside...
1,business,311.txt,Stormy year for property insurers\n\nA string ...,stormy year for property insurers a string of ...
2,business,365.txt,Nasdaq planning $100m-share sale\n\nThe owner ...,nasdaq planning mshare sale the owner of the t...
3,business,107.txt,Liberian economy starts to grow\n\nThe Liberia...,liberian economy starts to grow the liberian e...
4,business,304.txt,Bombardier chief to leave company\n\nShares in...,bombardier chief to leave company shares in tr...
5,business,110.txt,Japanese growth grinds to a halt\n\nGrowth in ...,japanese growth grinds to a halt growth in jap...

### removing stopwords

In [15]:
import nltk

nltk.download('stopwords')

from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [16]:
# remove stopwords

stop_words = set(stopwords.words('english'))

In [17]:
custom_stopwords = {
    "said", "would", "could", "also",
    "say", "told", "one", "new",
    "year", "years", "week",
    "last", "next", "may",
    "make", "made", "added",
    "bbc", "people", "time"
}

In [18]:
news_csv['clean_text'] = news_csv['clean_text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop_words)]))

In [19]:
news_csv['clean_text'] = news_csv['clean_text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (custom_stopwords)]))

In [20]:
news_csv['clean_text'].head(1).tolist()

['iran budget seeks state selloffs irans president mohammad khatami unveiled budget designed expand public spending loosen islamic republics dependence oil budget fiscal starting march calls selloff states corporate holdings mr khatamis second term president ends august making budget opposition members parliament attacked previous privatisations block plans elections ousted many mr khatamis supporters parliament favour hardline religious conservatives late backed law give parliament veto foreign investment ruling response involvement telecoms airport projects turkish companies hardliners accused business israel came long expediency council irans ultimate decisionmaker blessed mr khatamis policy selling stakes sectors protected constitution energy transport telecoms banking continued obstruction foreign investment get way privatisation plans mr khatamis hope modestly reducing governments reliance oil revenues address majlis mr khatami predicted economic growth current wanted increase budget trillion rials bn bn previous trillion within figure taxation rise bn rise expected current contrast oil revenues expected fall bn bn march current government expenditure come tax revenues mr khatami oil revenues used productive investment mr khatami already blocked parliament reducing subsidies many products including bread petrol reducing room manoeuvre']

### removing short words (noise)

In [21]:
tokens = news_csv['clean_text'].apply(
    lambda words: [w for w in words.split() if len(w) > 2]
)

In [22]:
news_csv['tokens'] = tokens

In [23]:
news_csv.head()

,category,filename,text,clean_text,tokens
0,business,412.txt,Iran budget seeks state sell-offs\n\nIran's pr...,iran budget seeks state selloffs irans preside...,"[iran, budget, seeks, state, selloffs, irans, ..."
1,business,311.txt,Stormy year for property insurers\n\nA string ...,stormy property insurers string storms typhoon...,"[stormy, property, insurers, string, storms, t..."
2,business,365.txt,Nasdaq planning $100m-share sale\n\nThe owner ...,nasdaq planning mshare sale owner technologydo...,"[nasdaq, planning, mshare, sale, owner, techno..."
3,business,107.txt,Liberian economy starts to grow\n\nThe Liberia...,liberian economy starts grow liberian economy ...,"[liberian, economy, starts, grow, liberian, ec..."
4,business,304.txt,Bombardier chief to leave company\n\nShares in...,bombardier chief leave company shares train pl...,"[bombardier, chief, leave, company, shares, tr..."

In [24]:
news_csv['tokens'].apply(len).describe()

count    2225.000000
mean      196.986067
std       115.250370
min        43.000000
25%       128.000000
50%       172.000000
75%       241.000000
max      2034.000000
Name: tokens, dtype: float64

### lemmetization using nltk

In [25]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

this process does:
playing -> play,
running -> run

convert the word into base form

In [26]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

news_csv["lemmas"] = news_csv["tokens"].apply(
    lambda tokens: [lemmatizer.lemmatize(word) for word in tokens]
)

### converting list to string

In [27]:
news_csv['lda_text'] = news_csv['lemmas'].apply(
    lambda x: ' '.join(x)
)

In [28]:
news_csv.head()

,category,filename,text,clean_text,tokens,lemmas,lda_text
0,business,412.txt,Iran budget seeks state sell-offs\n\nIran's pr...,iran budget seeks state selloffs irans preside...,"[iran, budget, seeks, state, selloffs, irans, ...","[iran, budget, seek, state, selloff, iran, pre...",iran budget seek state selloff iran president ...
1,business,311.txt,Stormy year for property insurers\n\nA string ...,stormy property insurers string storms typhoon...,"[stormy, property, insurers, string, storms, t...","[stormy, property, insurer, string, storm, typ...",stormy property insurer string storm typhoon e...
2,business,365.txt,Nasdaq planning $100m-share sale\n\nThe owner ...,nasdaq planning mshare sale owner technologydo...,"[nasdaq, planning, mshare, sale, owner, techno...","[nasdaq, planning, mshare, sale, owner, techno...",nasdaq planning mshare sale owner technologydo...
3,business,107.txt,Liberian economy starts to grow\n\nThe Liberia...,liberian economy starts grow liberian economy ...,"[liberian, economy, starts, grow, liberian, ec...","[liberian, economy, start, grow, liberian, eco...",liberian economy start grow liberian economy s...
4,business,304.txt,Bombardier chief to leave company\n\nShares in...,bombardier chief leave company shares train pl...,"[bombardier, chief, leave, company, shares, tr...","[bombardier, chief, leave, company, share, tra...",bombardier chief leave company share train pla...

# Vectorization

## Word Vectorization to check similarities

### Word2Vec, TfIdf, countvectorizer

-------------------------------------

r1: [car automobile vehicle]
r2: [car driving]

this 3 are unrelated words [Logically they're related for humans, but for mathematics it isn't]

-------------------------------------
countvectorizer =>
r1: [1 1 1]
r2: [2 1 0]
It counts the words but not understand meaning.

-------------------------------------
TFIDF => Term freq * Inverse Document freq

eg. government (appears only in political docs, gets high importance)

eg. said (appears everywhere, gets lowest importance), but still car != automobile
Good for similarity.

-------------------------------------

Word2Vec => Learns vector representation from context,

eg. r1[car automobile vehicle]

eg vector conversion.
r1[[0.12, 0.8, 0.1...][0.11, 0.7, -0.1...][0.13, 0.7, -0.5...]

Although r1 has 3 unknown words, but contextually their vectors will be nearby, so when we make clusters it appears so well.

-------------------------------------
decision: Word2Vec
-------------------------------------

In [29]:
! pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.6.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.2.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 59.0 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [30]:
# Using Lemmetized words to create vectors

from gensim.models import Word2Vec

sentences = news_csv["lemmas"].tolist()

# training word2vec model
w2v_model = Word2Vec(
    sentences=sentences,
    vector_size=100,
    window=5,
    min_count=3,
    workers=4,
    sg=1  # Skip-Gram
)

In [31]:
# Evaluation in simple terms

w2v_model.wv.most_similar("market")

[('stock', 0.7214646935462952),
 ('manufacturer', 0.6844290494918823),
 ('investor', 0.6776865124702454),
 ('housing', 0.6765967011451721),
 ('trend', 0.6745057702064514),
 ('exchange', 0.6641865968704224),
 ('jupiter', 0.6538578867912292),
 ('europe', 0.6492794156074524),
 ('gartner', 0.6448674201965332),
 ('demand', 0.6434873938560486)]

interpretation: news generally have similar topics like a stock market news, manufacturing of something, house selling market rate etc...

taking similar examples to check generalization

In [32]:
w2v_model.wv.most_similar("trend")

[('manufacturer', 0.959890604019165),
 ('grow', 0.9562829732894897),
 ('booming', 0.9358765482902527),
 ('improving', 0.9331409931182861),
 ('continues', 0.9321044087409973),
 ('driven', 0.9312752485275269),
 ('popularity', 0.9254755973815918),
 ('growing', 0.9246687889099121),
 ('predicts', 0.9233679175376892),
 ('improvement', 0.9209932684898376)]

In [33]:
w2v_model.wv.most_similar("stock")

[('exchange', 0.8891773819923401),
 ('share', 0.885711133480072),
 ('trading', 0.8642793297767639),
 ('investor', 0.853985607624054),
 ('nasdaq', 0.8503184914588928),
 ('listing', 0.8412228226661682),
 ('penny', 0.8241620659828186),
 ('closed', 0.8195772767066956),
 ('cairn', 0.7939420342445374),
 ('capital', 0.7844090461730957)]

In [34]:
print(f"Company: {w2v_model.wv.most_similar("company")} \n profit: {w2v_model.wv.most_similar("profit")
} \n Bank: {w2v_model.wv.most_similar("bank")}")

Company: [('firm', 0.8501873016357422), ('giant', 0.7452182769775391), ('asset', 0.7347562909126282), ('unit', 0.7290835976600647), ('fiat', 0.7268470525741577), ('gas', 0.719517171382904), ('business', 0.7190399169921875), ('bought', 0.7170504927635193), ('gazprom', 0.716022253036499), ('shareholder', 0.7153484225273132)]
 profit: [('revenue', 0.9250878691673279), ('earnings', 0.9091435074806213), ('euro', 0.8829324841499329), ('steel', 0.8657204508781433), ('pretax', 0.8538036346435547), ('posted', 0.8520843386650085), ('risen', 0.8453477025032043), ('rose', 0.8417691588401794), ('fuel', 0.8415409922599792), ('worldwide', 0.8330610990524292)]
 Bank: [('loan', 0.7294816970825195), ('reserve', 0.7217724323272705), ('monetary', 0.6935746073722839), ('central', 0.6884835958480835), ('account', 0.6841117143630981), ('lender', 0.6828210353851318), ('ratesetting', 0.6623970866203308), ('capital', 0.6621193885803223), ('china', 0.6608009338378906), ('raised', 0.6598235964775085)]

In [35]:
print(w2v_model.wv.most_similar("government"))
print(w2v_model.wv.most_similar("player"))
print(w2v_model.wv.most_similar("software"))
print(w2v_model.wv.most_similar("film"))

[('change', 0.7462551593780518), ('reform', 0.7369738817214966), ('policy', 0.7140024900436401), ('regulation', 0.7135103344917297), ('immigration', 0.7080827951431274), ('argued', 0.7044445872306824), ('welfare', 0.7042416334152222), ('congress', 0.7036283612251282), ('transport', 0.7030194997787476), ('mp', 0.7025432586669922)]
[('fan', 0.7744144797325134), ('fantastic', 0.7215718626976013), ('display', 0.7187051177024841), ('theyve', 0.7135449647903442), ('exciting', 0.7076088190078735), ('english', 0.6999385356903076), ('experience', 0.6951949000358582), ('lover', 0.6948719024658203), ('stuff', 0.6924708485603333), ('osullivan', 0.6921393871307373)]
[('program', 0.8708984851837158), ('tool', 0.8523720502853394), ('window', 0.8344153761863708), ('desktop', 0.8327166438102722), ('microsoft', 0.8253467679023743), ('pirated', 0.8188337087631226), ('microsofts', 0.8074164390563965), ('server', 0.8064063191413879), ('linux', 0.8052049875259399), ('version', 0.8049076795578003)]
[('movie', 0.6903413534164429), ('screen', 0.6669989228248596), ('hollywood', 0.643518328666687), ('festival', 0.6342235803604126), ('award', 0.6263923645019531), ('studio', 0.6244538426399231), ('cinema', 0.6158568263053894), ('star', 0.6104557514190674), ('documentary', 0.6025082468986511), ('actor', 0.5977447628974915)]

a good generalization, focuses on related contextual correct words.

## Document Vectorization
Word -> Documents
to check similarity of nearby vectors

following  common approach:
Document Vector = Average(All Word Vectors)

1 document = average of all vectors in a 1

In [36]:
import numpy as np

def document_vector(doc):
    vectors = [
        w2v_model.wv[word]
        for word in doc
        if word in w2v_model.wv
    ]

    if len(vectors) == 0:
        return np.zeros(w2v_model.vector_size)

    return np.mean(vectors, axis=0)

In [37]:
doc_vectors = np.array([
    document_vector(doc)
    for doc in news_csv["lemmas"]
])

In [38]:
doc_vectors[1]

array([ 0.0327821 ,  0.10828152,  0.14796044, -0.07286486,  0.08268796,
       -0.27661568,  0.19779254,  0.21592717, -0.04948396, -0.22420649,
       -0.09730912, -0.07891699,  0.02694909, -0.24880365, -0.00320426,
       -0.00490728,  0.2131611 ,  0.02221334,  0.0926797 , -0.17351663,
        0.2643854 , -0.04452675, -0.00989722,  0.03484925, -0.1289062 ,
       -0.20368427,  0.00566414, -0.15282772, -0.23565644, -0.18126978,
        0.05745904,  0.24592543, -0.06577042,  0.03532904, -0.17977554,
        0.09131438, -0.02918496, -0.22074917,  0.03749942, -0.14156464,
        0.31943995, -0.12116314,  0.04554363, -0.18464792,  0.16542219,
        0.0304544 , -0.166123  , -0.0810651 ,  0.19553615,  0.0132932 ,
       -0.03288525, -0.11635108,  0.03274422, -0.06137222, -0.10609393,
        0.03369148,  0.01777626,  0.08458603, -0.13522507, -0.05537147,
        0.08459915, -0.11116728, -0.16619326, -0.01103984, -0.3491895 ,
        0.29836112,  0.2001394 , -0.04004904, -0.28112832,  0.07524101,
       -0.0808687 ,  0.12194551, -0.04158847, -0.07393827, -0.02771023,
        0.15533523,  0.09913733,  0.25283313, -0.1619177 , -0.08176974,
        0.0319835 ,  0.03960048, -0.33437818,  0.2864387 , -0.18854935,
        0.08860201,  0.18473084,  0.23618649,  0.22061847, -0.09562798,
        0.11263279,  0.02248624,  0.04537739,  0.20723194,  0.17879398,
        0.26636404,  0.11393838, -0.09813353,  0.0539043 , -0.09818982],
      dtype=float32)

In [39]:
print(doc_vectors.shape)

#2225 total documents (rows) as per our dataset & total 100 vectors in each document

(2225, 100)

In [40]:
# finding cosine similarity

from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(
    [doc_vectors[1]],
    doc_vectors
)

In [41]:
similarities.argsort()[0][-10:]

array([ 28, 490, 263, 403, 260, 176, 240, 421, 397,   1])

In [42]:
list_last_10 = similarities.argsort()[0][-10:]

for i in list_last_10:
    print(f"{i} : Domain: {news_csv.iloc[i]['category']} & {news_csv.iloc[i]['text']}")

28 : Domain: business & Giant waves damage S Asia economy

Governments, aid agencies, insurers and travel firms are among those counting the cost of the massive earthquake and waves that hammered southern Asia.

The worst-hit areas are Sri Lanka, India, Indonesia and Thailand, with at least 23,000 people killed. Early estimates from the World Bank put the amount of aid needed at about $5bn (Â£2.6bn), similar to the cash offered Central America after Hurricane Mitch. Mitch killed about 10,000 people and caused damage of about $10bn in 1998. World Bank spokesman Damien Milverton told the Wall Street Journal that he expected an aid package of financing and debt relief.

Tourism is a vital part of the economies of the stricken countries, providing jobs for 19 million people in the south east Asian region, according to the World Travel and Tourism Council (WTTC). In the Maldives islands, in the Indian ocean, two-thirds of all jobs depend on tourism.

But the damage covers fishing, farming and businesses too, with hundreds of thousands of buildings and small boats destroyed by the waves. International agencies have pledged their support; most say it is impossible to gauge the extent of the damage yet. The International Monetary Fund (IMF) has promised rapid action to help the governments of the stricken countries cope.

"The IMF stands ready to do its part to assist these nations with appropriate support in their time of need," said managing director Rodrigo Rato. Only Sri Lanka and Bangladesh currently receive IMF support, while Indonesia, the quake's epicentre, has recently graduated from IMF assistance. It is up to governments to decide if they want IMF help. Other agencies, such as the Asian Development Bank, have said that it is too early to comment on the amount of aid needed. There is no underestimating the size of the problem, however. The United Nations' emergency relief coordinator, Jan Egeland, said that "this may be the worst national disaster in recent history because it is affecting so many heavily populated coastal areas... so many vulnerable communities. "Many people will have [had] their livelihoods, their whole future destroyed in a few seconds." He warned that "the longer term effects many be as devastating as the tidal wave or the tsunami itself" because of the risks of epidemics from polluted drinking water.

Insurers are also struggling to assess the cost of the damage, but several big players believe the final bill is likely to be less than the $27bn cost of the hurricanes that battered the US earlier this year.

"The region that's affected is very big so we have to check country-by-country what the situation is", said Serge Troeber, deputy head of the natural disasters department at Swiss Re, the world's second biggest reinsurance firm. "I should assume, however, that the overall dimension of insured damages is below the storm damages of the US," he said. Munich Re, the world's biggest reinsurer, said: "This is primarily a human tragedy. It is too early for us to state what our financial burden will be." Allianz has said it sees no significant impact on its profitability. However, a low insurance bill may simply reflect the general poverty of much of the region, rather than the level of economic devastation for those who live there.

The International Federation of the Red Cross and Red Crescent Societies told the Reuters news agency that it was seeking $6.5m for emergency aid.

"The biggest health challenges we face is the spread of waterborne diseases, particularly malaria and diarrhoea," the aid agency was quoted as saying. The European Union has said it will deliver 3m euros (Â£2.1m; $4.1m) of aid, according to the Wall Street Journal. The EU's Humanitarian Aid Commissioner, Louis Michel, was quoted as saying that it was key to bring aid "in those vital hours and days immediately after the disaster". Other countries also are reported to have pledged cash, while the US State Department said it was examining what aid was needed in the region. Getting companies and business up and running also may play a vital role in helping communities recover from the weekend's events.

Many of the worst-hit areas, such as Sri Lanka, Thailand's Phuket island and the Maldives, are popular tourist resorts that are key to local economies.

December and January are two of the busiest months for the travel in southern Asia and the damage will be even more keenly felt as the industry was only just beginning to emerge from a post 9/11 slump. Growth has been rapid in southeast Asia, with the World Tourism Organisation figures showing a 45% increase in tourist revenues in the region during the first 10 months of 2004. In southern Asia that expansion is 23%. "India continues to post excellent results thanks to increased promotion and product development, but also to the upsurge in business travel driven by the rapid economic development of the country," the WTO said. "Arrivals to other destinations such as... Maldives and Sri Lanka also thrived." In Thailand, tourism accounts for about 6% of the country's annual gross domestic product, or about $8bn. In Singapore the figure is close to 5%. Tourism also brings in much needed foreign currency. In the short-term, however, travel companies are cancelling flights and trips. That has hit shares across Asia and Europe, with investors saying that earnings and economic growth are likely to slow.

490 : Domain: business & Yangtze Electric's profits double

Yangtze Electric Power, the operator of China's Three Gorges Dam, has said its profits more than doubled in 2004.

The firm has benefited from increased demand for electricity at a time when power shortages have hit cities and provinces across the country. As a hydroelectric-power generator it has not been hurt by higher coal costs. Net income jumped to 3bn yuan in 2004 ($365m; Â£190m), compared with 1.4bn yuan in 2003. Sales surged to 6.2bn yuan, from 3bn yuan a year earlier. The figures topped analysts expectations, even though the rate of growth has slowed from 2003. Analysts forecast that it is likely to decline further this year to a rate of expansion of closer to 20%.

Yangtze Electric has been expanding its output to meet demand driven by China's booming economy. The government has delayed the building of a number of power plants in an effort to rein in growth amid concerns that the economy may overheat. That has led to an energy crunch, with demand outstripping supply. Earlier this month, work was halted on an underground power station, and a supply unit on the Three Gorges Dam, as well as a power station on its sister Xiluodu dam because of environmental worries. A total of 30 large-scale projects have been halted across the country for similar reasons. The Three Gorges Dam project has led to more than half a million people being relocated and drawn criticism from environmental groups and overseas human rights activists. Its sister project, the Xiluodu Dam, is being built on the Jinshajiang - or "river of golden sand" as the upper reaches of the Yangtze are known.

263 : Domain: business & Tsunami slows Sri Lanka's growth

Sri Lanka's president has launched a reconstruction drive worth $3.5bn (Â£1.8bn) by appealing for peace and national unity.

President Kumaratunga said it was now important to find a peaceful solution to years of internal conflict. Meanwhile, the International Monetary Fund (IMF) said damage from the tsunami would cut one percentage point from Sri Lanka's economic growth this year. It estimated the wave left physical damage equal to 6.5% of the economy.

Separately, the International Labour Organisation (ILO) said that at least one million people have lost their livelihoods in Sri Lanka and Indonesia alone. It called for action to create jobs. President Kumaratunga attended a ceremony in the southern town of Hambantota. She was joined by government and opposition politicians, together with Buddhist, Hindu, Muslim and Christian clergy.

Prime Minister Mahinda Rajapakse laid the foundation stone on a new housing project intended to provide 6,000 homes for survivors of the tsunami. Mrs Kumaratunga called for the tragedy to be "the start of a new beginning to rebuild our nation". "We are a country blessed with so many natural resources and we have not made use of them fully. Instead we have been squabbling, fighting," she added. Norway's peace negotiator Erik Solheim is due to arrive on Wednesday to try to revive peace talks in the decades-long conflict between government forces and the Tamil Tigers, who want a separate state in the north east of the country. Reconstruction efforts in eastern Sri Lanka have been hampered by tensions between the two sides.

The IMF said that the Sri Lankan authorities' initial estimates have put the physical damage at $1.3 to $1.5bn, but added that the implications for the economy were much wider than this. "The broader macroeconomic impact will clearly be substantial but the details are difficult to assess at this early stage," the IMF said. Growth, inflation, the balance of payments and foreign exchange reserves are all expected to show the effects of lost businesses and reconstruction costs. "The fishing industry has been devastated, agricultural production may be affected and tourism will suffer, especially in the short term," the report said. The ILO estimated that 400,000 Sri Lankans have lost their jobs, mostly in these three industries. Earnings from tourism this year are expected to be 15% lower than last year. Economic growth this year is expected to be 4%, which is about 1% less than previously forecast. Inflation could climb to 14% compared to a previous estimate of 12%. Although major exports have not suffered, the IMF expects the reconstruction effort will require higher imports which could damage the balance of payments. Foreign exchange reserves may become strained as "Sri Lanka will be hard pressed to keep international reserves at the pre-tsunami level" which totalled more than two months worth of imports. Last week, the IMF approved Sri Lanka's request for a freeze on loan repayments.

403 : Domain: business & Madagascar completes currency switch

Madagascar has completed the replacement of its Malagasy franc with a new currency, the ariary.

From Monday, all prices and contracts will have to be quoted in the ariary, which was trading at 1,893 to the US dollar. The Malagasy franc, which lost almost half its value in 2004, is no longer legal tender but will remain exchangeable at banks until 2009. The phasing out of the franc, begun in July 2003, was intended to distance the country from its past under French colonial rule and address the problem of the large amount of counterfeit francs in circulation. "It's above all a question of sovereignty," Reuters quoted a central bank official as saying. "It is symbolic of our independence from the old colonial ways. Since we left the French monetary zone in 1973 we should have our own currency with its own name." The ariary was the name of a pre-colonial currency in the Indian Ocean island state.

260 : Domain: business & Nigeria to boost cocoa production

The government of Nigeria is hoping to triple cocoa production over the next three years with the launch of an ambitious development programme.

Agriculture Minister Adamu Bello said the scheme aimed to boost production from an expected 180,000 tonnes this year to 600,000 tonnes by 2008. The government will pump 154m naira ($1.1m; Â£591,000) into subsidies for farming chemicals and seedlings. Nigeria is currently the world's fourth-largest cocoa producer.

Cocoa was the main export product in Nigeria during the 1960s. But with the coming of oil, the government began to pay less attention to the cocoa sector and production began to fall from a peak of about 400,000 tonnes a year in 1970. At the launch of the programme in the south-western city of Ibadan, Mr Bello explained that an additional aim of the project is to encourage the processing of cocoa in the country and lift local consumption. He also announced that 91m naira of the funding available had been earmarked for establishing cocoa plant nurseries. The country could be looking to emulate rival Ghana, which produced a bumper crop last year. However, some farmers are sceptical about the proposals. "People who are not farming will hijack the subsidy," said Joshua Osagie, a cocoa farmer from Edo state told Reuters. "The farmers in the village never see any assistance," he added.

At the same time as Nigeria announced its new initiative, Ghana - the world's second largest cocoa exporter - announced revenues from the industry had broken new records. The country saw more than $1.2bn-worth of the beans exported during 2003-04. Analysts said high tech-production techniques and crop spraying introduced by the government led to the huge crop, pushing production closer to levels seen in the 1960s when the country was the world's leading cocoa grower.

176 : Domain: business & Algeria hit by further gas riots

Algeria suffered a weekend of violent protests against government plans to raise gas prices, local press reports.

Demonstrators in a number of regions blocked roads, attacked public buildings and overturned vehicles, newspapers including El Watan reported. The price of butane gas, a vital fuel for cooking, has risen to 200 dinars ($2.77) per canister from 170 dinars. Even before the hike, failing economic conditions had been fanning resentment in some of Algeria's poorest regions.

Demonstrators took to the streets last week when the cost change was first announced, but police seemed to have restored order. According to local press reports, trouble flared up again on Saturday and carried on into Sunday. El Watan said that a number of hot spots centred on the villages and towns close to Bouira, about 100 kilometres (60 miles) south of the capital Algiers. Among the other main areas affected were the western Tiaret region and Sidi Ammar in the east of the country, Agence France Presse (AFP) reported. Riots also flared up in the Maghnia region close to the border with Morocco in the west, AFP said. Butane gas and fuel oil are used as the main source of fuel to heat homes and cook food in Algeria's remote mountain areas.

240 : Domain: business & Asia shares defy post-quake gloom

Thailand has become the first of the 10 southern Asian nations battered by giant waves at the weekend to cut its economic forecast.

Thailand's economy is now expected to grow by 5.7% in 2005, rather than 6% as forecast before tsunamis hit six tourist provinces. The full economic costs of the disaster remain unclear. In part, this is because of its scale, and because delivering aid and recovering the dead remain priorities. But Indonesian, Indian and Hong Kong stock markets reached record highs on Wednesday, suggesting that investors do not fear a major economic impact.

The highs showed the gap in outlook between investors in large firms and individuals who have lost their livelihoods.

Investors seemed to feel that some of the worst-affected areas - such as Aceh in Indonesia - were so under-developed that the tragedy would little impact on Asia's listed companies, according to analysts. "Obviously with a lot of loss of life, a lot of time is needed to clean up the mess, bury the people and find the missing. But it's not necessarily a really big thing in the economic sense," said ABN Amro chief Asian strategist Eddie Wong. India's Bombay Stock Exchange inched slightly above its previous record close on Wednesday. Expectations of strong corporate earnings in 2005 drove the Indonesian stock exchange in Jakarta to a record high on Wednesday. In Hong Kong, the Hang Seng index may be benefiting in part from the potential for its listed property companies to gain from rebuilding contracts in the tsunami-affected regions of South East Asia. In Sri Lanka, some economists have said that as much as 1% of annual growth may be lost. Sri Lanka's stock market has fallen about 5% since the weekend, but it is still 40% higher than at the start of 2004.

Thailand may lose 30bn baht (Â£398m; $768m) in earnings from tourism over the next three months, according to tourism minister Sontaya Kunplome.

In the affected provinces, he expects the loss of tourism revenue to be offset by government reconstruction spending. Thailand intends to spend a similar sum - around 30bn baht - on the rebuilding work. "It will take until the fourth quarter of next year before tourist visitors in Phuket and five other provinces return to their normal level," said Naris Chaiyasoot, director general at the ministry's fiscal policy office. In the Maldives the cost of reconstruction could wipe out economic growth, according to a government spokesman. "Our nation is in peril here," said Ahmed Shaheed, the chief government spokesman. He estimated the economic cost of the disaster at hundreds of millions of dollars. The Maldives has gross domestic product of $660m. "It won't be surprising if the cost exceeds our GDP," he said. "In the last few years, we made great progress in our standard of living - the United Nations recognised this. Now we see this can disappear in a few days, a few minutes." Shaheed noted that investment in a single tourist resort - the economic mainstay - could run to $40m. Between 10 and 12 of the 80-odd resorts have been severely damaged, and a similar number have suffered significant damage. However, many experts, including the World Bank, have pointed out that it is still difficult to assess the magnitude of the disaster and its likely economic impact.

421 : Domain: business & Disaster claims 'less than $10bn'

Insurers have sought to calm fears that they face huge losses after an earthquake and giant waves killed at least 38,000 people in southern Asia.

Munich Re and Swiss Re, the world's two biggest reinsurers, have said exposure will be less than for other disasters. Rebuilding costs are likely to be cheaper than in developed countries, and many of those affected will not have insurance, analysts said. Swiss Re has said total claims are likely to be less than $10bn (Â£5.17bn). Swiss Re believes that the cost would be substantial but that it is unlikely to be in double-digit billions, the Financial Times reported. Munich Re, the world's largest reinsurance company, said that its exposure is less than 100m euros (Â£70m; $136m).

At least 10 countries have been affected, with Sri Lanka, Indonesia, India and Thailand among the worst hit. The region's resorts and Western tourists are expected to be among the main claimants.

Lloyds of London told the Financial Times it expected its exposure to be limited to "holiday resorts, personal accident, travel insurance and marine risks". A spokeswoman for Hanover Re, Europe's fifth-largest reinsurance firm, estimated tsunami-related damage claims would be in the low double-digit millions of euros. The company has paid out about 300 million euros (Â£281m; $400m) to cover damage caused recently by four major hurricanes in the US.

But insurers have not had long to assess the economic impact of the damage and reports of more casualties and destruction are still coming through.

"So many things are unclear, it is just too early to tell," said Serge Troeber, deputy head of Swiss Re's natural disasters department. "You need very complicated processes to estimate damages. Unlike the hurricanes, you can't just run a model." He anticipated that his own company's total claims would be less then those from the hurricanes, which the company put at $640m. Allianz, a leading German insurer, said it did not know yet what its exposure would be. However, it said the tidal waves were unlikely to have a "significant" impact on its business. Zurich Financial said they could not yet assess the cost of the disaster.

The impact on US insurance companies is not expected to be heavy, analysts said.


News traversing: Last -> first

oil article
->
other oil articles
->
energy market articles

news top 10

In [43]:
list_top_10 = similarities.argsort()[0][:10]

In [44]:
for i in list_top_10:
  print(f"{i} : Domain: {news_csv.iloc[i]['category']} & {news_csv.iloc[i]['text']}")

1608 : Domain: entertainment & Stars gear up for Bafta ceremony

Film stars from across the globe are preparing to walk the red carpet at this year's Bafta award ceremony.

The 2005 Orange British Academy Film Awards are being held at The Odeon in London's Leicester Square. A host of Hollywood stars, including Cate Blanchett, Leonardo DiCaprio, Keanu Reeves and Richard Gere, are expected to attend Saturday's ceremony. Hosted by Stephen Fry, the glittering ceremony will be broadcast on BBC One at 2010 GMT.

Other actors expected to add to the glamour of the biggest night in UK film are Gael Garcia Bernal, Imelda Staunton, Diane Kruger, Christian Slater, Anjelica Huston, Helen Mirren and former James Bond star Pierce Brosnan. Hollywood blockbuster The Aviator, starring DiCaprio, leads the field with 14 nominations, including best film.

It is up against Eternal Sunshine of the Spotless Mind, Finding Neverland, The Motorcycle Diaries and British film Vera Drake, which has 11 nominations. British hope Imelda Staunton is one of the favourites to land the best actress award for her gritty role as a backstreet abortionist in the small-budget film. Other nominees in the best actress category include Charlize Theron for Monster, Ziyi Zhang for House of Flying Daggers and UK star Kate Winslet, who has two nods for her roles in Eternal Sunshine of the Spotless Mind and Finding Neverland.

DiCaprio faces competition from Bernal, Jamie Foxx, Jim Carrey and Johnny Depp in the best actor category. And British actor Clive Owen is hoping to repeat his Golden Globe success with a best supporting actor award for his role in Closer. His co-star Natalie Portman is up against Blanchett, Heather Craney, Julie Cristie and Meryl Streep in the best supporting actress category. Mike Leigh is up for the best director award for Vera Drake, alongside Martin Scorsese for The Aviator, Michael Mann for Collateral, Michel Gondry for Eternal Sunshine of the Spotless Mind and Marc Forster for Finding Neverland.

1759 : Domain: entertainment & US critics laud comedy Sideways

Road trip comedy Sideways has had more praise heaped on it by two US critics' associations, adding to honours it has already picked up.

The Chicago Film Critics Association (CFCA) named it winner in five categories including best film and best actor for Paul Giamatti. But the director award went to Clint Eastwood for Million Dollar Baby. The Southeastern Film Critics also awarded Sideways its best film of the year accolade. Director Alexander Payne was named best director, and he also won best screenplay shared with Jim Taylor. The CFCA awarded Thomas Haden Church the best supporting actor prize and Virginia Madsen the best supporting actress award for their roles in the film.

Sideways has already been voted best film by critics associations in New York and Los Angeles and has been nominated for a Golden Globe. British actress Imelda Staunton won the CFCA best actress for the gritty abortion drama Vera Drake, adding to a growing list of awards she has won for her performance in the Mike Leigh film. Scrubs star Zach Braff was named best new director for his debut Garden State. Michael Moore's controversial documentary Fahrenheit 9/11 won the best documentary, while A Very Long Engagement won best foreign film. The Chicago critics have yet to name a date for when their awards ceremony will be held.

1635 : Domain: entertainment & Wine comedy wins critics' award

Quirky comedy Sideways was named the best film of the year by the Los Angeles Film Critics Association.

The US movie also picked up four other accolades including best director for Alexander Payne and supporting actor for Thomas Haden Church. British actress Imelda Staunton has again been recognised for her role in Vera Drake, winning best actress, while Liam Neeson won best actor for Kinsey. The awards will be handed out on 13 January at a ceremony in Las Vegas.

Sideways tells the story of two men who take a road trip through California's wine regions and also stars Paul Giamatti. Virginia Madsen was also named best supporting actress for her performance in the film. House of Flying Daggers, directed by Yimou Zhang, was named best foreign language film, while the animation award went to The Incredibles. Unusually, the runners-up in categories were also named with Clint Eastwood's Million Dollar Baby just missing out on the best film award. The best director runner-up was Martin Scorsese for The Aviator. A career achievement award will be handed to veteran actor and comic Jerry Lewis at the ceremony next year.

1738 : Domain: entertainment & Bookmakers back Aviator for Oscar

The Aviator has been tipped by UK bookmakers as the favourite to win the best film award at this year's Oscars.

Ray star Jamie Foxx is clear favourite in the best actor category while Million Dollar Baby's Hilary Swank is tipped to win the best actress prize. Bookmakers predict Cate Blanchett will be named best supporting actress. William Hill and Ladbrokes have given The Aviator 4/9 and 8/13 odds of winning best film, with Million Dollar Baby in second place at 9/4.

Bet Direct and Bet 365 also tip The Aviator, with the majority of bookmakers regarding Finding Neverland as the outsider. The Aviator is also widely tipped to win the best director prize for Martin Scorsese. British star Clive Owen is second favourite at William Hill to take the best supporting actor award, for his performance in Closer. The favourite in that category is Sideways star Thomas Hayden Church. Vera Drake star Imelda Staunton has 5/1 odds of winning the best actress Oscar at Bet 365 and William Hill, ahead of fellow UK star Kate Winslet who has odds of 25/1 at William Hill.

Mike Leigh is the outsider in the best director category for Vera Drake, a position he holds jointly with Ray's Taylor Hackford at bookmakers VC Bet. This year's Academy Awards will be handed out in Hollywood on 27 February. X Factor judge Sharon Osbourne will present Sky television's live coverage of the event. Meanwhile, Clive Owen's best supporting actor nomination has led a bookmaker to shorten his odds of becoming the next James Bond. He has moved from 4/1 to 5/2 favourite to play 007, with Hugh Jackman and Ewan McGregor joint second favourite. "Clive Owen's nomination has sparked a betting frenzy from James Bond fans, who feel that his heightened global recognition will have done his chances of becoming the next Bond a world of good," said William Hill spokesman Rupert Adams.

1577 : Domain: entertainment & Bookmakers back Aviator for Oscar

The Aviator has been tipped by UK bookmakers as the favourite to win the best film award at this year's Oscars.

Ray star Jamie Foxx is clear favourite in the best actor category while Million Dollar Baby's Hilary Swank is tipped to win the best actress prize. Bookmakers predict Cate Blanchett will be named best supporting actress. William Hill and Ladbrokes have given The Aviator 4/9 and 8/13 odds of winning best film, with Million Dollar Baby in second place at 9/4.

Bet Direct and Bet 365 also tip The Aviator, with the majority of bookmakers regarding Finding Neverland as the outsider. The Aviator is also widely tipped to win the best director prize for Martin Scorsese. British star Clive Owen is second favourite at William Hill to take the best supporting actor award, for his performance in Closer. The favourite in that category is Sideways star Thomas Hayden Church. Vera Drake star Imelda Staunton has 5/1 odds of winning the best actress Oscar at Bet 365 and William Hill, ahead of fellow UK star Kate Winslet who has odds of 25/1 at William Hill.

Mike Leigh is the outsider in the best director category for Vera Drake, a position he holds jointly with Ray's Taylor Hackford at bookmakers VC Bet. This year's Academy Awards will be handed out in Hollywood on 27 February. X Factor judge Sharon Osbourne will present Sky television's live coverage of the event. Meanwhile, Clive Owen's best supporting actor nomination has led a bookmaker to shorten his odds of becoming the next James Bond. He has moved from 4/1 to 5/2 favourite to play 007, with Hugh Jackman and Ewan McGregor joint second favourite. "Clive Owen's nomination has sparked a betting frenzy from James Bond fans, who feel that his heightened global recognition will have done his chances of becoming the next Bond a world of good," said William Hill spokesman Rupert Adams.

1452 : Domain: entertainment & Oscar nominees gear up for lunch

Leonardo DiCaprio, Jamie Foxx and Hilary Swank are among those due to attend this year's Oscar nominees luncheon on Monday.

They will join more than 100 nominees from the 24 Oscar categories at the annual event, which will take place at the Beverly Hilton hotel, Los Angeles. British hopefuls, including Kate Winslet, Imelda Staunton and Sophie Okonedo are also expected to attend. This year's Oscar ceremony will be held on Sunday 27 February.

Martin Scorsese's The Aviator is leading the field at this year's Oscars with 11 nominations, while other multiple nominees include Million Dollar Baby and Sideways. Oscar nominees Swank and Foxx were among the winners at the Screen Actors Guild awards at the weekend, one of the many ceremonies held in the run-up to the Oscars. Swank won Best Actress for Million Dollar Baby while Foxx triumphed for his performance as Ray Charles in the biopic Ray. Sideways was also among the winners, taking the prize for best cast performance. The next major film award ceremony of the season is the Bafta awards, which take place at London's Odeon Leicester Square on 12 February. Many of those nominated for Oscars including DiCaprio, Foxx and Staunton - an Oscar nominee for her performance in Vera Drake - have also been nominated for Baftas.

1800 : Domain: entertainment & Critics back Aviator for Oscars

Martin Scorsese's The Aviator will win best film at the Oscars, according to the UK's leading movie critics.

But several of those surveyed by the BBC News website think the veteran film-maker will lose the best director prize to Clint Eastwood. Most of the critics tipped Jamie Foxx and Hilary Swank to scoop best actor and actress for Ray and Million Dollar Baby respectively. The jury comprised experts and critics from the top UK film publications. The panel also revealed which nominees they would personally prefer to win.

All expect The Aviator to win best film, but many think it will be a close race between Scorsese's Howard Hughes biopic and Eastwood's boxing drama Million Dollar Baby. The other films nominated are wine comedy Sideways, factual drama Finding Neverland, and Ray Charles biopic Ray.

"I'm pretty sure this is the year of The Aviator, though my own choice would be Sideways," said the Observer's Philip French. "Sideways should win but it doesn't have a hope," said Jamie Graham of Total Film, a position shared by Film 2005 presenter Jonathan Ross. "The form going in to the Oscars points to The Aviator, but I liked Million Dollar Baby more," said Tim Dams, news editor of trade weekly Screen International.

Five of the eight critics tipped Scorsese to win best director, with Mr Dams, Heat's Charles Gant and Empire's Angie Errigo plumping for Eastwood. Sideway's Alexander Payne, Ray's Taylor Hackford and British director Mike Leigh - nominated for period drama Vera Drake - are considered outsiders in this category. "Up until recently I could have sworn Scorsese would get it just for being Scorsese," Ms Errigo told the BBC News website. "But I'm beginning to think Eastwood will get it."

"I'd be very happy for Mike Leigh to win, but I don't think he has any chance," said Charles Gant, film editor of Heat. Foxx's portrayal of Ray Charles has already seen him win prizes at the Golden Globes, Baftas and Screen Actors Guild Awards. Mr Dams said this made him "out-and-out favourite" to be named best actor on Oscar night. "Everyone would be incredibly surprised if he didn't win," he said. "If you're a betting man, he's as close as you get to a certainty." "If Paul Giamatti was nominated for Sideways it would be a different game," says Total Film's Jamie Graham. "But Foxx will and should win."

With Vera Drake star Imelda Staunton nominated for best actress alongside Kate Winslet, Britain has a good chance of victory - on paper. Jonathan Ross, for one, will be very happy if Winslet wins for Eternal Sunshine of the Spotless Mind. But while Wendy Ide of The Times still thinks Staunton has a chance, Heat's Charles Gant believes her Bafta win will cut little ice with Academy voters. "I'd like Staunton to win, but her chances are not that great," said Mr Gant, who predicted a second Oscar for Hilary Swank.

"I think Swank will win," said Mr French. "Imelda has got as far as she's going to get playing that role." Staunton is also the personal choice of Steven Gaydos, executive editor of industry magazine Variety. But while he tipped Swank to win, he predicted it would be a close contest. "Everything has the ability to flip by one vote and go the other way," he told the BBC News website. "There's not a sense that it's obvious how it's going to go." Meanwhile, thousands of people have voted in a BBC Radio Five Live poll to find the best film never to have won a best picture Oscar. The audience voted overwhelmingly for The Shawshank Redemption, the 1994 Frank Darabont tale of hope and humanity, which received 52% of the online votes and 68% of the text messages. The other two finalists, Citizen Kane and A Matter of Life and Death split the remaining votes roughly equally. This year's Academy Awards will be shown in the UK by Sky Movies 1 at 0130 GMT on Monday.

- Tim Dams, Screen International: Film - The Aviator; director - Clint Eastwood; actor - Jamie Foxx; actress - Hilary Swank.

- Angie Errigo, Empire: Film - The Aviator; director - Clint Eastwood; actor - Jamie Foxx; actress - Hilary Swank.

- Philip French, The Observer: Film - The Aviator; director - Martin Scorsese; actor - Jamie Foxx; actress - Hilary Swank.

- Charles Gant, Heat: Film - The Aviator; director - Clint Eastwood; actor - Jamie Foxx; actress - Hilary Swank.

- Steven Gaydos, Variety: Film - The Aviator; director - Martin Scorsese; actor - Jamie Foxx; actress - Hilary Swank.

- Jamie Graham, Total Film: Film - The Aviator; director - Martin Scorsese; actor - Jamie Foxx; actress - Hilary Swank.

- Wendy Ide, The Times: Film - The Aviator; director - Martin Scorsese; actor - Jamie Foxx; actress - Imelda Staunton.

- Jonathan Ross, Film 2005: Film - The Aviator; director - Martin Scorsese; actor - Jamie Foxx; actress - Hilary Swank.

- Tim Dams, Screen International: Film - Million Dollar Baby; director - Clint Eastwood; actor - Jamie Foxx; actress - Hilary Swank.

- Angie Errigo, Empire: Film - The Aviator; director - Martin Scorsese; actor - Jamie Foxx; actress - Hilary Swank.

- Philip French, The Observer: Film - Sideways; director - Martin Scorsese; actor - Jamie Foxx; actress - Imelda Staunton.

- Charles Gant, Heat: Film - Sideways; director - Mike Leigh; actor - Jamie Foxx; actress - Imelda Staunton.

- Steven Gaydos, Variety: Film - Million Dollar Baby; director - Clint Eastwood; actor - Don Cheadle; actress - Imelda Staunton.

- Jamie Graham, Total Film: Film - Sideways; director - Alexander Payne; actor - Jamie Foxx; actress - Hilary Swank.

- Wendy Ide, The Times: Film - Sideways; director - Alexander Payne; actor - Don Cheadle; actress - Imelda Staunton.

- Jonathan Ross, Film 2005: Film - Sideways; director - Clint Eastwood; actor - Jamie Foxx; actress - Kate Winslet.

1529 : Domain: entertainment & Aviator wins top Globes accolades

The Aviator has been named best film at the Golden Globe Awards, with its star Leonardo DiCaprio named best actor.

Hollywood veteran Clint Eastwood took the best director prize for Million Dollar Baby while its star Hilary Swank was best actress. Quirky comedy Sideways was named best screenplay and best comedy. Ray star Jamie Foxx was best actor in a musical/comedy while Briton Clive Owen and Natalie Portman won prizes for best supporting roles in Closer.

The Aviator, in which DiCaprio plays millionaire Howard Hughes, edged ahead of its rivals at the Beverly Hills ceremony by winning the best original score prize. This give it a total of three awards while Million Dollar Baby, Sideways and Closer took two Golden Globes each. Accepting his best dramatic actor prize, DiCaprio described director Martin Scorsese as "one of the greatest contributors to the world of cinema of all time".

Annette Bening won best actress in a musical/comedy for Being Julia while Spanish movie The Sea Inside was named best foreign language film. Swank, who previously won the Golden Globe and Oscar for Boys Don't Cry, paid tribute to Million Dollar Baby director and co-star Clint Eastwood. "You guided us so brilliantly, while you also, in my humble opinion, gave the performance of your career," she said. Foxx was nominated for three awards but was beaten to the best supporting actor title by Owen and the best actor in a TV movie prize by Geoffrey Rush in The Life and Death of Peter Sellers.

A BBC co-production, The Life and Death of Peter Sellers was also named best TV movie. Mick Jagger and Dave Stewart won the best original song award for Old Habits Die Hard from movie re-make Alfie, while Ian McShane was named best actor in a TV drama for his lead role in Deadwood.

Other UK hopes Kate Winslet and Imelda Staunton went home empty-handed despite lead actress nominations for Eternal Sunshine of the Spotless Mind and Vera Drake respectively. Winning a Golden Globe is said to improve a film or performer's chance of subsequently winning an Academy Award. Unlike the Oscars, the Golden Globes split awards by genre - one prize for dramas and the other for musicals and comedies. The Globes also honour the best in television, with suburban series Desperate Housewives named best TV comedy show. Actress Teri Hatcher beat fellow Desperate Housewives stars Marcia Cross and Felicity Huffman to the best comedy actress prize.

Hatcher thanked the show's cast, crew and "a network who gave me a second chance at a career when I couldn't have been a bigger 'has been'". Cosmetic surgery series Nip/Tuck beat The Sopranos and Deadwood to the best television drama title. Arrested Development star Jason Bateman was named best TV actor in a musical or comedy series. The Golden Globes are awarded by the Hollywood Foreign Press Association, comprising film reporters based in Los Angeles and working for overseas outlets. Robin Williams, a five-time Globe winner for such films as The Fisher King and Good Morning, Vietnam, received the Cecil B DeMille award for career achievement. He dedicated his prize to Superman actor Christopher Reeve, who died last year.

1798 : Domain: entertainment & Actor Foxx sees Globe nominations

US actor Jamie Foxx has been given two nominations for Golden Globe awards, with Meryl Streep, Morgan Freeman and Cate Blanchett also up for prizes.

The stars were shortlisted on Monday for supporting roles, with the main nominations still to come. Foxx has starred in Collateral and Ray. Clive Owen, David Carradine and Natalie Portman are also up for awards. The Golden Globes, Hollywood's second most prominent awards, are the first major nominations to be announced. Last year, The Lord Of the Rings: The Return Of the King was named best drama movie while Lost In Translation won best musical or comedy. Sean Penn, Charlize Theron, Tim Robbins and Renee Zellweger all won acting awards - mirroring the eventual Oscars outcome. The Golden Globes ceremony will take place on 16 January, with the Oscars following on 27 February.

1495 : Domain: entertainment & Baby becomes new Oscar favourite

Clint Eastwood's boxing drama Million Dollar Baby has become the new favourite to win best picture at the Oscars on Sunday.


# K-Means Clustering

In [45]:
from sklearn.cluster import KMeans

In [46]:
# Starting with cluste centroids k=5 (same as bbc's output classes)
def clusters(k) :
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    clusters = kmeans.fit_predict(doc_vectors)

    news_csv[f"cluster_k={k}"] = clusters

In [47]:
clusters(5)

In [48]:
news_csv.head()

,category,filename,text,clean_text,tokens,lemmas,lda_text,cluster_k=5
0,business,412.txt,Iran budget seeks state sell-offs\n\nIran's pr...,iran budget seeks state selloffs irans preside...,"[iran, budget, seeks, state, selloffs, irans, ...","[iran, budget, seek, state, selloff, iran, pre...",iran budget seek state selloff iran president ...,4
1,business,311.txt,Stormy year for property insurers\n\nA string ...,stormy property insurers string storms typhoon...,"[stormy, property, insurers, string, storms, t...","[stormy, property, insurer, string, storm, typ...",stormy property insurer string storm typhoon e...,4
2,business,365.txt,Nasdaq planning $100m-share sale\n\nThe owner ...,nasdaq planning mshare sale owner technologydo...,"[nasdaq, planning, mshare, sale, owner, techno...","[nasdaq, planning, mshare, sale, owner, techno...",nasdaq planning mshare sale owner technologydo...,4
3,business,107.txt,Liberian economy starts to grow\n\nThe Liberia...,liberian economy starts grow liberian economy ...,"[liberian, economy, starts, grow, liberian, ec...","[liberian, economy, start, grow, liberian, eco...",liberian economy start grow liberian economy s...,4
4,business,304.txt,Bombardier chief to leave company\n\nShares in...,bombardier chief leave company shares train pl...,"[bombardier, chief, leave, company, shares, tr...","[bombardier, chief, leave, company, share, tra...",bombardier chief leave company share train pla...,0

In [49]:
pd.crosstab(
    news_csv["category"],
    news_csv["cluster_k=5"]
)

cluster_k=5      0    1    2    3    4
category
business       217    0   16    8  269
entertainment   51  317    9    0    9
politics       138    3    4  269    3
sport           38  473    0    0    0
tech            38   25  331    1    6

Before removal of extra stopwords:

k=5 was the best cluster


politics: 447/511 are in cluster 2

business: 102/510 are in cluster 2

there maybe government businesses mentioned somewhere related.

In [50]:
clusters(6)

In [51]:
pd.crosstab(
    news_csv["category"],
    news_csv["cluster_k=6"]
)

cluster_k=6      0    1    2    3    4    5
category
business         5    1  221  268    0   15
entertainment    0  250   53    7   68    8
politics       254    0  154    2    3    4
sport            0   74   32    0  405    0
tech             1   10   40    5   21  324

after adding extra stopwords, k=6 give well generalized and more structured output

In [52]:
cluster_docs = news_csv[
    news_csv["cluster_k=6"] == 3
]

from collections import Counter

words = [
    word
    for doc in cluster_docs["lemmas"]
    for word in doc
]

print("business aligned with politics")
Counter(words).most_common(50)

business aligned with politics

[('market', 375),
 ('growth', 365),
 ('economy', 342),
 ('sale', 323),
 ('price', 317),
 ('rate', 279),
 ('economic', 252),
 ('month', 238),
 ('bank', 222),
 ('share', 221),
 ('rise', 215),
 ('profit', 199),
 ('company', 196),
 ('analyst', 195),
 ('country', 192),
 ('dollar', 192),
 ('figure', 186),
 ('government', 185),
 ('firm', 176),
 ('oil', 172),
 ('euro', 169),
 ('world', 159),
 ('however', 155),
 ('china', 155),
 ('quarter', 152),
 ('expected', 150),
 ('cost', 150),
 ('job', 150),
 ('million', 148),
 ('spending', 138),
 ('december', 133),
 ('strong', 132),
 ('rose', 128),
 ('business', 126),
 ('demand', 126),
 ('fall', 125),
 ('consumer', 124),
 ('cut', 123),
 ('high', 122),
 ('interest', 119),
 ('increase', 116),
 ('since', 115),
 ('hit', 115),
 ('trade', 111),
 ('first', 110),
 ('export', 107),
 ('chief', 106),
 ('report', 105),
 ('budget', 104),
 ('economist', 104)]

Yukos was one of the largest and most successful Russian oil and gas companies.

Former majority shareholders launched massive international arbitrations against the Russian government for the expropriation of the company. Courts have ruled that Russia's actions were politically motivated to seize the company's assets.


SO this cluster is aligned in political + business way!

in terms of fraud/legal business issues

In [53]:
cluster_docs = news_csv[
    news_csv["cluster_k=6"] == 2
]

from collections import Counter

words = [
    word
    for doc in cluster_docs["lemmas"]
    for word in doc
]

print("business")
Counter(words).most_common(50)

business

[('company', 516),
 ('government', 476),
 ('firm', 417),
 ('law', 335),
 ('court', 303),
 ('case', 269),
 ('group', 261),
 ('right', 256),
 ('two', 255),
 ('minister', 249),
 ('country', 238),
 ('plan', 223),
 ('deal', 211),
 ('executive', 201),
 ('month', 191),
 ('yukos', 191),
 ('bank', 191),
 ('chief', 190),
 ('share', 190),
 ('state', 190),
 ('report', 184),
 ('world', 179),
 ('police', 176),
 ('business', 172),
 ('home', 172),
 ('decision', 169),
 ('market', 168),
 ('first', 167),
 ('legal', 167),
 ('take', 165),
 ('public', 165),
 ('work', 164),
 ('service', 162),
 ('many', 161),
 ('part', 160),
 ('say', 158),
 ('charge', 155),
 ('foreign', 153),
 ('three', 151),
 ('day', 148),
 ('however', 148),
 ('former', 147),
 ('want', 146),
 ('bid', 141),
 ('trial', 141),
 ('news', 140),
 ('action', 140),
 ('european', 140),
 ('offer', 139),
 ('spokesman', 139)]

In [54]:
cluster_docs = news_csv[
    news_csv["cluster_k=6"] == 0
]

from collections import Counter

words = [
    word
    for doc in cluster_docs["lemmas"]
    for word in doc
]

print("Politics")
Counter(words).most_common(50)

Politics

[('labour', 714),
 ('party', 663),
 ('election', 627),
 ('blair', 523),
 ('tory', 458),
 ('government', 436),
 ('minister', 394),
 ('brown', 350),
 ('tax', 330),
 ('howard', 294),
 ('plan', 267),
 ('prime', 259),
 ('leader', 254),
 ('lord', 236),
 ('chancellor', 234),
 ('public', 216),
 ('issue', 209),
 ('conservative', 201),
 ('general', 198),
 ('campaign', 192),
 ('britain', 192),
 ('country', 170),
 ('tony', 166),
 ('vote', 165),
 ('lib', 158),
 ('claim', 153),
 ('say', 152),
 ('secretary', 149),
 ('michael', 147),
 ('voter', 143),
 ('political', 139),
 ('liberal', 138),
 ('cut', 133),
 ('get', 131),
 ('policy', 131),
 ('kennedy', 128),
 ('democrat', 127),
 ('two', 126),
 ('home', 126),
 ('mp', 126),
 ('council', 121),
 ('take', 117),
 ('want', 117),
 ('think', 116),
 ('budget', 113),
 ('change', 113),
 ('local', 112),
 ('back', 111),
 ('ukip', 111),
 ('way', 110)]

In [55]:
clusters(4)

In [56]:
pd.crosstab(
    news_csv["category"],
    news_csv["cluster_k=4"]
)

cluster_k=4      0    1    2    3
category
business       112    1   16  381
entertainment   21  335   20   10
politics       400    3    6    8
sport           37  474    0    0
tech            24   25  343    9

In [57]:
clusters(7)

In [58]:
pd.crosstab(
    news_csv["category"],
    news_csv["cluster_k=7"]
)

cluster_k=7      0    1    2    3    4    5    6
category
business       267    0  217    6   14    0    6
entertainment    7   14   24    0    6  161  174
politics         2    0  142  254    2    0   17
sport            0  311   26    0    0    4  170
tech             6    2   35    1  315    4   38

# Most Important Finding

Word2Vec embeddings revealed that the BBC Business category contains at least two distinct semantic groups: Economic/Market reporting and Corporate/Legal reporting. Increasing the number of clusters from 5 to 6 separated these sub-domains naturally, suggesting that editorial categories do not fully represent the underlying semantic structure of the news corpus.

# Finding silhuette score
to check goodness of datapoints into specific cluster

higher silhuette score = better fit.

In [62]:
doc_vectors.shape

(2225, 100)

In [64]:
from sklearn.metrics import silhouette_score

In [65]:
for k in range(2, 11):
  k_means = KMeans(
      n_clusters = k,
      random_state = 42,
      n_init = 10
  )

  labels = k_means.fit_predict(doc_vectors)

  score = silhouette_score(doc_vectors, labels)
  print(f"Silhouette Score for k={k}: {score}")

Silhouette Score for k=2: 0.269417405128479
Silhouette Score for k=3: 0.23188316822052002
Silhouette Score for k=4: 0.24794228374958038
Silhouette Score for k=5: 0.23652146756649017
Silhouette Score for k=6: 0.19626785814762115
Silhouette Score for k=7: 0.19056151807308197
Silhouette Score for k=8: 0.1874990165233612
Silhouette Score for k=9: 0.18639788031578064
Silhouette Score for k=10: 0.18980436027050018

Conclusion:

Silhouette Score identified k=2 as the most compact clustering solution.

However, qualitative analysis showed that k=5 and k=6 produced substantially more interpretable topic structures corresponding to real-world news domains such as Politics, Technology, Sports, Entertainment, and distinct Business subtopics.

This highlights the difference between geometric cluster quality and semantic interpretability in topic discovery tasks.